import { lazy, Suspense, useEffect, useState } from 'react'
import { useForm } from 'react-hook-form'
import { motion } from 'framer-motion'
import { FiAlertCircle, FiArrowRight, FiCheck, FiChevronDown, FiCompass, FiFeather, FiLayers, FiPlay, FiZap } from 'react-icons/fi'
import { Link } from 'react-router-dom'
import { articles, faqs, topics } from '../data/content'

const ParticleField = lazy(() => import('../components/three/ParticleField').then((module) => ({ default: module.ParticleField })))
const reveal = { initial: { opacity: 0, y: 22 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, amount: 0.2 }, transition: { duration: 0.65 } }
type SubscribeForm = { email: string }

function Subscribe() {
  const [complete, setComplete] = useState(false)
  const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<SubscribeForm>({ mode: 'onBlur' })
  const submit = async () => { await new Promise((resolve) => setTimeout(resolve, 450)); setComplete(true) }
  if (complete) return <div role="status" className="flex items-center gap-2 rounded-full border border-emerald-400/30 bg-emerald-400/10 px-5 py-3 text-sm text-emerald-300"><FiCheck /> You’re on the list.</div>
  return <form onSubmit={handleSubmit(submit)} noValidate className="w-full max-w-md">
    <div className="flex flex-col gap-3 sm:flex-row"><input {...register('email', { required: 'Enter your email address.', pattern: { value: /^\S+@\S+\.\S+$/, message: 'Enter a valid email address.' } })} type="email" inputMode="email" autoComplete="email" aria-label="Email address" aria-invalid={Boolean(errors.email)} aria-describedby={errors.email ? 'subscribe-error' : undefined} placeholder="you@domain.com" className="h-12 min-w-0 flex-1 rounded-full border border-white/10 bg-white/[.04] px-5 text-sm outline-none transition placeholder:text-zinc-600 focus:border-cyan-300 focus:ring-2 focus:ring-cyan-300/20" /><button className="button-primary !py-3 disabled:cursor-wait disabled:opacity-70" disabled={isSubmitting} type="submit">{isSubmitting ? 'Adding you…' : <>Subscribe <FiArrowRight /></>}</button></div>
    {errors.email && <p id="subscribe-error" className="mt-2 flex items-center gap-1 text-left text-xs text-amber-300"><FiAlertCircle /> {errors.email.message}</p>}
  </form>
}

export function Home() {
  const [openFaq, setOpenFaq] = useState<number | null>(0)
  const [showParticles, setShowParticles] = useState(false)
  useEffect(() => { const media = window.matchMedia('(min-width: 768px) and (prefers-reduced-motion: no-preference)'); const update = () => setShowParticles(media.matches); update(); media.addEventListener('change', update); return () => media.removeEventListener('change', update) }, [])
  return <main><div className="noise" />
    <section className="relative isolate min-h-[min(850px,100svh)] overflow-hidden pt-20">{showParticles && <Suspense fallback={null}><ParticleField /></Suspense>}<div className="absolute inset-0 -z-10 bg-[radial-gradient(ellipse_at_50%_15%,rgba(0,212,255,.12),transparent_34%),radial-gradient(ellipse_at_78%_30%,rgba(124,58,237,.12),transparent_28%)]" />
      <div className="container-site relative flex min-h-[calc(100svh-5rem)] flex-col justify-center pb-20 pt-24 sm:min-h-[760px]"><motion.div {...reveal} className="mb-7 flex items-center gap-3"><span className="h-2 w-2 rounded-full bg-cyan-300 shadow-[0_0_18px_#00D4FF]" /><span className="eyebrow">The weekly intelligence brief · issue 042</span></motion.div><motion.h1 {...reveal} transition={{ duration: .8, delay: .08 }} className="max-w-5xl font-display text-[clamp(3.5rem,9vw,8.75rem)] font-bold leading-[.88] tracking-[-.075em]">AI, decoded.<br /><span className="text-zinc-500">Weekly.</span></motion.h1><motion.p {...reveal} transition={{ duration: .7, delay: .16 }} className="mt-8 max-w-xl text-base leading-7 text-zinc-400 sm:text-lg">A calm signal on artificial intelligence, machine learning and the people building tomorrow. Read in five minutes. Think about it all week.</motion.p><motion.div {...reveal} transition={{ duration: .7, delay: .24 }} className="mt-9 flex flex-wrap gap-3"><a className="button-primary" href="#subscribe">Start reading <FiArrowRight /></a><Link className="button-ghost" to="/issues"><FiPlay className="text-cyan-300" /> Read latest issue</Link></motion.div><motion.div {...reveal} transition={{ delay: .35 }} className="mt-16 flex items-center gap-5 text-xs text-zinc-500"><div className="flex -space-x-2" aria-hidden="true">{['bg-cyan-400', 'bg-violet-500', 'bg-orange-400', 'bg-emerald-400'].map((color) => <i key={color} className={`h-7 w-7 rounded-full border-2 border-ink ${color}`} />)}</div><span>Join 14,000+ curious minds every Sunday</span></motion.div></div>
    </section>
    <section className="section"><motion.div {...reveal} className="container-site"><div className="mb-8 flex items-end justify-between gap-5"><div><p className="eyebrow">This week’s signal</p><h2 className="mt-3 font-display text-3xl font-bold tracking-[-.05em] sm:text-5xl">A sharper kind of brief.</h2></div><Link to="/issues" className="hidden text-sm text-cyan-300 sm:block">Browse archive →</Link></div><article className="group relative overflow-hidden rounded-[2rem] border border-white/10 bg-surface p-6 sm:p-10 lg:grid lg:grid-cols-[1.1fr_.9fr] lg:gap-12"><div className="absolute -right-24 -top-24 h-80 w-80 rounded-full bg-violet-500/15 blur-3xl" /><div className="relative"><span className="eyebrow">Issue 042 · July 27, 2026</span><h3 className="mt-5 max-w-xl font-display text-3xl font-bold leading-tight tracking-[-.055em] sm:text-5xl">The interfaces that make intelligence feel useful.</h3><p className="mt-6 max-w-lg leading-7 text-zinc-400">From agentic browsers to ambient tools, this week we follow the design decisions shaping our relationship with capable systems.</p><div className="mt-8 flex items-center gap-4 text-xs text-zinc-500"><span>08 min read</span><span className="h-1 w-1 rounded-full bg-zinc-600" /><span>7 stories, 3 ideas</span></div><Link to="/issues" className="button-ghost mt-8">Open issue <FiArrowRight /></Link></div><div className="relative mt-10 min-h-64 overflow-hidden rounded-2xl border border-white/10 bg-[#171525] p-7 lg:mt-0"><div className="absolute -right-8 top-0 h-48 w-48 rounded-full bg-cyan-300/30 blur-3xl" /><div className="relative flex h-full flex-col justify-between"><div className="flex items-center justify-between font-mono text-[10px] tracking-widest text-cyan-200"><span>NEXUS/DB</span><span>042</span></div><p className="max-w-[240px] font-display text-3xl font-bold leading-[.95] tracking-[-.06em]">Useful intelligence is designed.</p><div className="flex gap-2"><i className="h-2 w-2 rounded-full bg-cyan-300" /><i className="h-2 w-2 rounded-full bg-violet-400" /><i className="h-2 w-2 rounded-full bg-white/30" /></div></div></div></article></motion.div></section>
    <section className="section border-y border-white/[.07] bg-white/[.015]"><div className="container-site"><motion.div {...reveal} className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">From the database</p><h2 className="mt-3 font-display text-3xl font-bold tracking-[-.05em] sm:text-5xl">Things worth your focus.</h2></div><Link to="/articles" className="text-sm text-cyan-300">View all articles →</Link></motion.div><div className="mt-12 grid gap-5 md:grid-cols-3">{articles.map((article, index) => <motion.div {...reveal} transition={{ delay: index * .08 }} key={article.title}><Link to="/articles" className="group block rounded-2xl border border-white/[.08] bg-[#0e0e0e] p-4 transition duration-300 hover:-translate-y-1 hover:border-white/20 hover:shadow-card focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-300"><div className={`h-44 overflow-hidden rounded-xl bg-gradient-to-br ${article.tone} p-5`}><div className="flex h-full items-end"><span className="rounded-full border border-white/15 bg-black/20 px-3 py-1 text-[10px] font-medium uppercase tracking-widest text-white/80">{article.category}</span></div></div><div className="p-2 pt-5"><h3 className="font-display text-xl font-bold leading-snug tracking-[-.035em] group-hover:text-cyan-100">{article.title}</h3><p className="mt-4 text-xs text-zinc-500">{article.time}<span className="float-right text-zinc-300 transition group-hover:translate-x-1">Read →</span></p></div></Link></motion.div>)}</div></div></section>
    <section className="section"><div className="container-site grid gap-12 lg:grid-cols-[.72fr_1.28fr]"><motion.div {...reveal}><p className="eyebrow">Why NexusDB</p><h2 className="mt-3 font-display text-4xl font-bold tracking-[-.055em] sm:text-5xl">Less noise.<br />More knowing.</h2><p className="mt-6 max-w-sm leading-7 text-zinc-400">No hot takes, no content treadmill. Just the pieces that remain useful after the feed has moved on.</p></motion.div><div className="grid gap-px overflow-hidden rounded-2xl border border-white/10 bg-white/10 sm:grid-cols-3">{[[FiCompass, 'Find the signal', 'A discerning filter for a field moving at full speed.'], [FiFeather, 'Feel the clarity', 'Ideas explained without flattening their complexity.'], [FiLayers, 'Build context', 'Recurring threads that turn headlines into understanding.']].map(([Icon, title, text]) => { const IconComponent = Icon as typeof FiCompass; return <motion.div {...reveal} key={title as string} className="bg-ink p-7"><IconComponent className="text-cyan-300" /><h3 className="mt-10 font-display text-lg font-bold">{title as string}</h3><p className="mt-3 text-sm leading-6 text-zinc-500">{text as string}</p></motion.div> })}</div></div></section>
    <section className="border-y border-white/[.07] py-10"><div className="overflow-hidden"><div className="marquee flex w-max gap-10 whitespace-nowrap font-display text-3xl font-bold tracking-[-.05em] text-zinc-700 sm:text-5xl">{[...topics, ...topics].map((topic, index) => <span key={`${topic}-${index}`}>{topic}<b className="ml-10 text-cyan-300">✦</b></span>)}</div></div></section>
    <section className="section"><div className="container-site"><motion.div {...reveal} className="mb-12 text-center"><p className="eyebrow">A growing curiosity</p><h2 className="mt-3 font-display text-3xl font-bold tracking-[-.05em] sm:text-5xl">A small, brilliant corner of the internet.</h2></motion.div><div className="grid grid-cols-2 divide-x divide-y divide-white/10 overflow-hidden rounded-2xl border border-white/10 lg:grid-cols-4">{[['14K+', 'Subscribers'], ['184', 'Articles'], ['42', 'Weekly issues'], ['68', 'Countries']].map(([number, label]) => <div key={label} className="bg-white/[.018] p-6 text-center sm:p-10"><strong className="font-display text-4xl font-bold tracking-[-.06em] sm:text-5xl">{number}</strong><p className="mt-2 text-xs uppercase tracking-widest text-zinc-500">{label}</p></div>)}</div></div></section>
    <section className="section border-t border-white/[.07]"><div className="container-site grid gap-12 lg:grid-cols-[.75fr_1.25fr]"><motion.div {...reveal}><p className="eyebrow">Common questions</p><h2 className="mt-3 font-display text-4xl font-bold tracking-[-.055em]">The good kind of inbox?</h2></motion.div><div>{faqs.map(([question, answer], index) => <div key={question} className="border-b border-white/10"><button onClick={() => setOpenFaq(openFaq === index ? null : index)} aria-expanded={openFaq === index} aria-controls={`faq-${index}`} className="flex w-full items-center justify-between py-6 text-left text-base font-medium transition hover:text-cyan-100 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-300"><span>{question}</span><FiChevronDown className={`transition ${openFaq === index ? 'rotate-180 text-cyan-300' : ''}`} /></button>{openFaq === index && <p id={`faq-${index}`} className="max-w-xl pb-6 pr-10 text-sm leading-7 text-zinc-400">{answer}</p>}</div>)}</div></div></section>
    <section id="subscribe" className="section"><div className="container-site"><motion.div {...reveal} className="relative overflow-hidden rounded-[2rem] border border-white/10 bg-[#121317] px-6 py-16 text-center sm:px-12 sm:py-24"><div className="absolute left-1/2 top-0 h-80 w-80 -translate-x-1/2 -translate-y-1/2 rounded-full bg-violet-500/20 blur-[100px]" /><div className="relative mx-auto flex max-w-2xl flex-col items-center"><FiZap className="text-2xl text-cyan-300" /><p className="eyebrow mt-5">Sunday, considered</p><h2 className="mt-4 font-display text-4xl font-bold leading-none tracking-[-.06em] sm:text-6xl">Make room for<br />better ideas.</h2><p className="mt-6 max-w-md text-sm leading-6 text-zinc-400">The most interesting work in AI, handpicked and delivered once a week. No noise. No spam.</p><div className="mt-8"><Subscribe /></div><p className="mt-4 text-[11px] text-zinc-600">Free forever. Unsubscribe in one click.</p></div></motion.div></div></section>
  </main>
}
