import type { ReactNode } from 'react'; import { Helmet } from 'react-helmet-async'; import { Link } from 'react-router-dom'; import { motion } from 'framer-motion'; import { FiArrowRight, FiMail } from 'react-icons/fi'; import { articles, topics } from '../data/content'
const copy={about:['About NexusDB','A quieter way to follow the future.','NexusDB is an independent weekly publication for people who care about how intelligence changes the work, tools and cultures around us.'],archive:['The archive','A living record of what mattered.','Browse our long-form notes, deep dives and weekly issues, organized for return visits rather than churn.'],issues:['Weekly issues','One useful hour, condensed.','Every Sunday, a new snapshot of the ideas and developments worth carrying forward.'],articles:['Articles','The long view, in public.','Thoughtful writing on the systems, research, and human choices that shape technology.'],categories:['Explore topics','Follow your curiosity.','Cross-disciplinary thinking for an interdisciplinary field.'],resources:['The toolkit','Good work needs good references.','A carefully maintained collection of tools, papers, and places to learn.'],contact:['Say hello','A thoughtful inbox is always open.','Tips, feedback, interesting work — we’d genuinely love to hear from you.']} as const
type PageType=keyof typeof copy
function Shell({children,title,description}:{children:ReactNode,title:string,description:string}){return <main className="container-site min-h-[70vh] pb-24 pt-40"><Helmet><title>{title} — NexusDB</title><meta name="description" content={description}/></Helmet><motion.div initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} transition={{duration:.55}}>{children}</motion.div></main>}
function Header({type}:{type:PageType}){const [eyebrow,title,text]=copy[type];return <><p className="eyebrow">{eyebrow}</p><h1 className="mt-4 max-w-3xl font-display text-5xl font-bold tracking-[-.065em] sm:text-7xl">{title}</h1><p className="mt-7 max-w-xl text-lg leading-8 text-zinc-400">{text}</p></>}
export function DirectoryPage({type}:{type:PageType}){if(type==='categories')return <Shell title={copy[type][0]} description={copy[type][2]}><Header type={type}/><div className="mt-14 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{topics.map((topic,i)=><Link to="/articles" key={topic} className="group flex h-32 items-end justify-between rounded-2xl border border-white/10 bg-white/[.025] p-6 transition hover:-translate-y-1 hover:border-cyan-300/40"><span className="font-display text-xl font-bold tracking-[-.03em]">{topic}</span><span className="text-cyan-300 transition group-hover:translate-x-1">0{i+3} →</span></Link>)}</div></Shell>
if(type==='contact')return <Shell title={copy[type][0]} description={copy[type][2]}><Header type={type}/><a className="button-primary mt-12" href="mailto:hello@nexusdb.dev"><FiMail/> hello@nexusdb.dev</a></Shell>
if(type==='about')return <Shell title={copy[type][0]} description={copy[type][2]}><Header type={type}/><div className="mt-16 grid gap-6 border-t border-white/10 pt-8 md:grid-cols-3">{[['01','Curiosity over certainty'],['02','Depth over drama'],['03','Useful over urgent']].map(([n,t])=><div key={n}><p className="font-mono text-xs text-cyan-300">{n}</p><h2 className="mt-4 font-display text-2xl font-bold tracking-[-.04em]">{t}</h2></div>)}</div></Shell>
return <Shell title={copy[type][0]} description={copy[type][2]}><Header type={type}/><div className="mt-14 grid gap-4">{[...articles,...articles].map((a,i)=><article key={i} className="group flex flex-col justify-between gap-5 rounded-2xl border border-white/[.09] bg-white/[.02] p-6 transition hover:border-white/25 sm:flex-row sm:items-center"><div><p className="eyebrow">{type==='issues'?`Issue ${42-i}`:a.category}</p><h2 className="mt-2 font-display text-2xl font-bold tracking-[-.04em]">{a.title}</h2><p className="mt-2 text-sm text-zinc-500">{a.time} · NexusDB editorial desk</p></div><Link to="/articles" className="text-sm text-cyan-300">Read <FiArrowRight className="ml-1 inline"/></Link></article>)}</div></Shell>}
export function Privacy(){return <Shell title="Privacy" description="NexusDB privacy policy"><p className="eyebrow">Privacy</p><h1 className="mt-4 font-display text-5xl font-bold tracking-[-.065em]">Respect, by default.</h1><div className="mt-12 max-w-2xl space-y-8 text-sm leading-7 text-zinc-400"><p>NexusDB only collects your email address when you subscribe. We use it exclusively to deliver the newsletter and never sell or trade your information.</p><p>We use minimal, privacy-conscious analytics to understand aggregate readership. You can unsubscribe at any time from any issue.</p></div></Shell>}
export function NotFound(){return <Shell title="Not found" description="This page does not exist"><p className="font-mono text-sm text-cyan-300">404 / LOST IN THE GRAPH</p><h1 className="mt-5 font-display text-6xl font-bold tracking-[-.07em] sm:text-8xl">Nothing here<br/>but potential.</h1><Link className="button-primary mt-10" to="/">Return home <FiArrowRight/></Link></Shell>}
