#!/usr/bin/env python3
"""
NexusDB Knowledge Pipeline Automation Engine
Tracks, validates, and reports knowledge lifecycle status across:
  01_RAW/CAPTURE -> 01_RAW/PROCESS -> 02_NEW-KNOWLEDGE -> NODES / NOTES -> 03_MOC
"""

import os
import sys
import re
from pathlib import Path

# Add lib directory to path
sys.path.append(os.path.join(os.path.dirname(__file__), 'lib'))
try:
    from vault_paths import get_vault_root
    from vault_utils import parse_frontmatter
except ImportError:
    def get_vault_root():
        return os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))

# Force UTF-8 stdout encoding on Windows
if sys.platform.startswith('win'):
    import io
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')


def scan_capture(vault_root):
    capture_dir = Path(vault_root) / "01_RAW" / "CAPTURE"
    if not capture_dir.exists():
        return []
    return [f for f in capture_dir.glob("*.md") if f.name != ".gitkeep"]


def scan_process(vault_root):
    process_dir = Path(vault_root) / "01_RAW" / "PROCESS"
    if not process_dir.exists():
        return []
    return [f for f in process_dir.glob("*.md") if f.name != ".gitkeep"]


def scan_new_knowledge(vault_root):
    nk_dir = Path(vault_root) / "02_NEW-KNOWLEDGE"
    if not nk_dir.exists():
        return []
    
    candidates = []
    for f in nk_dir.glob("*.md"):
        if f.name == ".gitkeep":
            continue
        try:
            content = f.read_text(encoding="utf-8")
            if "Downstream Atomic Concept Candidates" in content:
                # Count candidate lines
                matches = re.findall(r"-\s*\[\[NODES/([^\]]+)\]\]:\s*(.+)", content)
                candidates.append({
                    "file": f,
                    "candidates": matches
                })
        except Exception:
            pass
    return candidates


def scan_nodes(vault_root):
    nodes_dir = Path(vault_root) / "NODES"
    if not nodes_dir.exists():
        return []
    return [f for f in nodes_dir.glob("*.md") if f.name != ".gitkeep"]


def generate_pipeline_report(vault_root, captures, processes, nk_candidates, nodes_count):
    reports_dir = Path(vault_root) / ".antigravity" / "reports"
    reports_dir.mkdir(parents=True, exist_ok=True)
    report_path = reports_dir / "pipeline-status.md"

    lines = [
        "# Knowledge Pipeline Status Report\n\n",
        "## 📊 Pipeline Summary\n\n",
        f"- **Pending Captures (`01_RAW/CAPTURE/`)**: {len(captures)}\n",
        f"- **Active Working Drafts (`01_RAW/PROCESS/`)**: {len(processes)}\n",
        f"- **Study Notes with Pending Candidates (`02_NEW-KNOWLEDGE/`)**: {len(nk_candidates)}\n",
        f"- **Total Permanent Atomic Nodes (`NODES/`)**: {nodes_count}\n\n",
        "---\n\n",
        "## 📥 1. Unprocessed Captures\n\n"
    ]

    if captures:
        lines.append("| Filename | Path |\n| :--- | :--- |\n")
        for c in captures:
            lines.append(f"| `{c.name}` | `01_RAW/CAPTURE/{c.name}` |\n")
    else:
        lines.append("*No pending raw captures in inbox.*\n")

    lines.append("\n## ⚙️ 2. Active Working Drafts\n\n")
    if processes:
        lines.append("| Filename | Status |\n| :--- | :--- |\n")
        for p in processes:
            lines.append(f"| `{p.name}` | Under active transformation |\n")
    else:
        lines.append("*No working drafts currently in process.*\n")

    lines.append("\n## 💡 3. Pending Downstream Atomization Candidates\n\n")
    if nk_candidates:
        for nk in nk_candidates:
            lines.append(f"### `02_NEW-KNOWLEDGE/{nk['file'].name}`\n")
            lines.append(f"Found {len(nk['candidates'])} atomic candidate(s):\n")
            for c_slug, c_desc in nk['candidates']:
                lines.append(f"- `[[NODES/{c_slug}]]`: {c_desc}\n")
            lines.append("\n")
    else:
        lines.append("*No pending atomic candidates found in study notes.*\n")

    lines.append("\n---\n*Report auto-generated by `knowledge_pipeline.py`*\n")

    report_path.write_text("".join(lines), encoding="utf-8")
    return report_path


def main():
    vault_root = get_vault_root()
    print("=" * 60)
    print("NexusDB Knowledge Pipeline Status Check")
    print("=" * 60)

    captures = scan_capture(vault_root)
    processes = scan_process(vault_root)
    nk_candidates = scan_new_knowledge(vault_root)
    nodes = scan_nodes(vault_root)

    report_path = generate_pipeline_report(vault_root, captures, processes, nk_candidates, len(nodes))

    print(f"[CAPTURE]        Pending raw inputs:  {len(captures)}")
    print(f"[PROCESS]        Active drafts:       {len(processes)}")
    print(f"[NEW-KNOWLEDGE]  Study notes w/ candidate atoms: {len(nk_candidates)}")
    print(f"[NODES]          Total atomic nodes:  {len(nodes)}")
    print("-" * 60)
    print(f"Pipeline status report updated: {report_path}")
    print("=" * 60)


if __name__ == "__main__":
    main()
