/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you intend to edit and debug this file, suggest using source map
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MindMapPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/mindmap/view.ts
var import_obsidian2 = require("obsidian");

// src/storage/parser.ts
var import_obsidian = require("obsidian");
var CURRENT_VERSION = "2.0";
var DEFAULT_VIEW_STATE = {
  zoom: 1,
  pan: { x: 0, y: 0 }
};
var GENERATED_BODY_START = "<!-- mindmap:content:start -->";
var GENERATED_BODY_END = "<!-- mindmap:content:end -->";
function createEmptyNode(content = "Central Topic") {
  return {
    id: crypto.randomUUID(),
    content,
    children: []
  };
}
function createEmptyMindMap() {
  return {
    version: CURRENT_VERSION,
    root: createEmptyNode(),
    connections: [],
    view: { ...DEFAULT_VIEW_STATE, pan: { ...DEFAULT_VIEW_STATE.pan } }
  };
}
function parseMindMap(content) {
  try {
    const frontmatterMatch = content.match(/^---\r?\n([\s\S]*?)\r?\n---/);
    if (!frontmatterMatch) {
      return null;
    }
    const data = (0, import_obsidian.parseYaml)(frontmatterMatch[1]);
    if (!isRecord(data) || !("mindmap" in data)) return null;
    return normalizeMindMap(data.mindmap);
  } catch (e) {
    console.error("Failed to parse mind map:", e);
    return null;
  }
}
function isRecord(value) {
  return typeof value === "object" && value !== null;
}
function normalizeMindMap(data) {
  if (!isRecord(data) || !("root" in data)) return null;
  return migrateMindMap({
    version: typeof data.version === "string" ? data.version : "1.0",
    root: normalizeNode(data.root),
    connections: normalizeConnections(data.connections),
    view: normalizeViewState(data.view)
  });
}
function migrateMindMap(data) {
  var _a, _b, _c, _d;
  if (!data.version || data.version === "1.0") {
    return {
      ...data,
      version: CURRENT_VERSION,
      connections: (_a = data.connections) != null ? _a : [],
      view: (_b = data.view) != null ? _b : { ...DEFAULT_VIEW_STATE, pan: { ...DEFAULT_VIEW_STATE.pan } }
    };
  }
  return {
    ...data,
    version: CURRENT_VERSION,
    connections: (_c = data.connections) != null ? _c : [],
    view: (_d = data.view) != null ? _d : { ...DEFAULT_VIEW_STATE, pan: { ...DEFAULT_VIEW_STATE.pan } }
  };
}
function normalizeNode(node) {
  var _a;
  if (Array.isArray(node)) {
    node = (_a = node[0]) != null ? _a : {};
  }
  const value = isRecord(node) ? node : {};
  return {
    id: typeof value.id === "string" ? value.id : crypto.randomUUID(),
    content: typeof value.content === "string" ? value.content : "Untitled",
    note: normalizeOptionalText(value.note),
    linkedFilePath: normalizeOptionalText(value.linkedFilePath),
    children: Array.isArray(value.children) ? value.children.map(normalizeNode) : [],
    collapsed: value.collapsed === true ? true : void 0,
    position: normalizePosition(value.position)
  };
}
function normalizePosition(position) {
  if (!isRecord(position) || typeof position.x !== "number" || typeof position.y !== "number") {
    return void 0;
  }
  return {
    x: position.x,
    y: position.y
  };
}
function normalizeOptionalText(value) {
  return typeof value === "string" && value.trim().length > 0 ? value : void 0;
}
function normalizeViewState(view) {
  var _a;
  if (!isRecord(view)) return void 0;
  const zoom = typeof view.zoom === "number" ? Math.min(2.5, Math.max(0.4, view.zoom)) : DEFAULT_VIEW_STATE.zoom;
  const pan = (_a = normalizePosition(view.pan)) != null ? _a : DEFAULT_VIEW_STATE.pan;
  return {
    zoom,
    pan: { ...pan }
  };
}
function normalizeConnections(connections) {
  if (!Array.isArray(connections)) return [];
  return connections.filter((connection) => isRecord(connection) && typeof connection.fromNodeId === "string" && typeof connection.toNodeId === "string").map((connection) => ({
    id: typeof connection.id === "string" ? connection.id : crypto.randomUUID(),
    fromNodeId: connection.fromNodeId,
    toNodeId: connection.toNodeId
  }));
}
function serializeMindMap(data, existingContent) {
  const yaml = (0, import_obsidian.stringifyYaml)({ mindmap: data });
  const existingBody = getUserBody(existingContent);
  const generatedBody = renderMindMapMarkdown(data);
  const body = [
    GENERATED_BODY_START,
    generatedBody,
    GENERATED_BODY_END,
    existingBody
  ].filter((part) => part.trim().length > 0).join("\n\n");
  return `---
${yaml}---

${body}
`;
}
function getUserBody(existingContent) {
  if (!existingContent) return "";
  const body = existingContent.replace(/^---\r?\n[\s\S]*?\r?\n---\r?\n?/, "").trim();
  return body.replace(
    new RegExp(`${escapeRegExp(GENERATED_BODY_START)}[\\s\\S]*?${escapeRegExp(GENERATED_BODY_END)}`, "m"),
    ""
  ).trim();
}
function renderMindMapMarkdown(data) {
  var _a;
  const lines = ["# Mind map", "", ...renderNodeLines(data.root, 0)];
  const connections = (_a = data.connections) != null ? _a : [];
  if (connections.length > 0) {
    lines.push("", "## Connections", "");
    for (const connection of connections) {
      const from = findNodeContent(data.root, connection.fromNodeId);
      const to = findNodeContent(data.root, connection.toNodeId);
      if (from && to) {
        lines.push(`- ${escapeMarkdownText(from)} -> ${escapeMarkdownText(to)}`);
      }
    }
  }
  return lines.join("\n");
}
function renderNodeLines(node, depth) {
  const indent = "  ".repeat(depth);
  const lines = [`${indent}- ${escapeMarkdownText(node.content)}`];
  if (node.note) {
    lines.push(`${indent}  - Note: ${escapeMarkdownText(node.note)}`);
  }
  if (node.linkedFilePath) {
    lines.push(`${indent}  - Linked note: [[${node.linkedFilePath.replace(/\.md$/i, "")}]]`);
  }
  for (const child of node.children) {
    lines.push(...renderNodeLines(child, depth + 1));
  }
  return lines;
}
function escapeMarkdownText(text) {
  return text.replace(/\r?\n/g, " ").trim() || "Untitled";
}
function findNodeContent(node, nodeId) {
  if (node.id === nodeId) return node.content;
  for (const child of node.children) {
    const found = findNodeContent(child, nodeId);
    if (found) return found;
  }
  return null;
}
function escapeRegExp(text) {
  return text.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

// src/mindmap/layout.ts
var CONFIG = {
  NODE_WIDTH: 120,
  NODE_HEIGHT: 40,
  HORIZONTAL_SPACING: 40,
  VERTICAL_SPACING: 30
};
function layoutTree(root) {
  var _a;
  const positions = /* @__PURE__ */ new Map();
  const depths = /* @__PURE__ */ new Map();
  function calculateDepth(node, depth = 0) {
    depths.set(node, depth);
    if (node.collapsed) return;
    for (const child of node.children) {
      calculateDepth(child, depth + 1);
    }
  }
  calculateDepth(root);
  const depthNodes = /* @__PURE__ */ new Map();
  for (const [node, depth] of depths) {
    if (!depthNodes.has(depth)) {
      depthNodes.set(depth, []);
    }
    depthNodes.get(depth).push(node);
  }
  for (const [depth, nodes] of depthNodes) {
    const y = depth * (CONFIG.NODE_HEIGHT + CONFIG.VERTICAL_SPACING);
    for (const node of nodes) {
      const existing = positions.get(node.id);
      positions.set(node.id, { x: (_a = existing == null ? void 0 : existing.x) != null ? _a : 0, y });
    }
  }
  const lastXAtDepth = /* @__PURE__ */ new Map();
  function calculateX(node) {
    var _a2;
    const visibleChildren = node.collapsed ? [] : node.children;
    if (visibleChildren.length === 0) {
      const yPos2 = positions.get(node.id).y;
      const depth = depths.get(node);
      const lastX = (_a2 = lastXAtDepth.get(depth)) != null ? _a2 : 0;
      const newX = lastX + CONFIG.NODE_WIDTH + CONFIG.HORIZONTAL_SPACING;
      positions.set(node.id, { x: newX, y: yPos2 });
      lastXAtDepth.set(depth, newX);
      return newX;
    }
    let firstChildX = null;
    let lastChildX = null;
    for (const child of visibleChildren) {
      const childX = calculateX(child);
      if (firstChildX === null) firstChildX = childX;
      lastChildX = childX;
    }
    const center = (firstChildX + lastChildX) / 2;
    const yPos = positions.get(node.id).y;
    positions.set(node.id, { x: center, y: yPos });
    return center;
  }
  calculateX(root);
  const rootPos = positions.get(root.id);
  const offsetX = -rootPos.x;
  for (const [id, pos] of positions) {
    positions.set(id, { x: pos.x + offsetX, y: pos.y });
  }
  return positions;
}

// src/mindmap/canvas.ts
var _MindMapCanvas = class _MindMapCanvas {
  constructor(container, callbacks) {
    this.svgElement = null;
    this.positions = /* @__PURE__ */ new Map();
    this.nodeElements = /* @__PURE__ */ new Map();
    this.visibleNodes = [];
    this.editingNodeId = null;
    this.connectSourceId = null;
    this.mergeSourceId = null;
    this.pan = { x: 0, y: 0 };
    this.dragState = null;
    this.boxSelectState = null;
    this.lastClickNodeId = null;
    this.lastClickAt = 0;
    this.lastContextMenuNodeId = null;
    this.lastContextMenuAt = 0;
    this.container = container;
    this.callbacks = callbacks;
  }
  render(root, connections, selectedNodeIds, connectSourceId, mergeSourceId, editingNodeId, zoom, pan) {
    this.visibleNodes = this.getVisibleNodes(root);
    this.positions = layoutTree(root);
    this.applySavedPositions();
    this.normalizePositions();
    this.connectSourceId = connectSourceId;
    this.mergeSourceId = mergeSourceId;
    this.editingNodeId = editingNodeId;
    this.pan = pan;
    this.createSVG();
    this.updateViewBox(zoom);
    this.renderEdges(root);
    this.renderConnections(connections);
    this.renderNodes(root, new Set(selectedNodeIds));
  }
  createSVG() {
    if (!this.svgElement) {
      this.svgElement = activeDocument.createElementNS("http://www.w3.org/2000/svg", "svg");
      this.svgElement.classList.add("mindmap-svg");
      this.svgElement.addEventListener("pointerdown", (event) => this.handleSvgPointerDown(event));
      this.svgElement.addEventListener("contextmenu", (event) => this.handleSvgContextMenu(event));
      this.svgElement.addEventListener("pointermove", (event) => this.handlePointerMove(event));
      this.svgElement.addEventListener("pointerup", (event) => this.handlePointerUp(event));
      this.svgElement.addEventListener("pointercancel", () => {
        this.dragState = null;
        this.boxSelectState = null;
      });
      this.container.appendChild(this.svgElement);
    }
    this.svgElement.innerHTML = "";
    this.nodeElements.clear();
  }
  getVisibleNodes(root) {
    const nodes = [];
    const visit = (node) => {
      nodes.push(node);
      if (node.collapsed) return;
      node.children.forEach(visit);
    };
    visit(root);
    return nodes;
  }
  applySavedPositions() {
    for (const node of this.visibleNodes) {
      if (node.position) {
        this.positions.set(node.id, { ...node.position });
      }
    }
  }
  normalizePositions() {
    if (this.positions.size === 0) return;
    let minX = Infinity;
    let minY = Infinity;
    for (const pos of this.positions.values()) {
      minX = Math.min(minX, pos.x - _MindMapCanvas.NODE_WIDTH / 2);
      minY = Math.min(minY, pos.y);
    }
    if (minX >= _MindMapCanvas.PADDING && minY >= _MindMapCanvas.PADDING) {
      return;
    }
    const offsetX = Math.max(0, _MindMapCanvas.PADDING - minX);
    const offsetY = Math.max(0, _MindMapCanvas.PADDING - minY);
    for (const [id, pos] of this.positions) {
      this.positions.set(id, {
        x: pos.x + offsetX,
        y: pos.y + offsetY
      });
    }
  }
  updateViewBox(zoom) {
    if (!this.svgElement || this.positions.size === 0) return;
    let maxX = 0;
    let maxY = 0;
    for (const pos of this.positions.values()) {
      maxX = Math.max(maxX, pos.x + _MindMapCanvas.NODE_WIDTH / 2);
      maxY = Math.max(maxY, pos.y + _MindMapCanvas.NODE_HEIGHT);
    }
    const width = Math.max(
      this.container.clientWidth,
      maxX + _MindMapCanvas.PADDING + Math.max(this.pan.x, 0)
    );
    const height = Math.max(
      this.container.clientHeight,
      maxY + _MindMapCanvas.PADDING + Math.max(this.pan.y, 0)
    );
    this.svgElement.setAttribute("viewBox", `0 0 ${width} ${height}`);
    this.svgElement.style.width = `${width * zoom}px`;
    this.svgElement.style.height = `${height * zoom}px`;
  }
  renderEdges(node) {
    const nodePos = this.positions.get(node.id);
    if (!nodePos || node.collapsed) return;
    for (const child of node.children) {
      const childPos = this.positions.get(child.id);
      if (!childPos) continue;
      this.renderEdge(nodePos, childPos);
      this.renderEdges(child);
    }
  }
  renderEdge(from, to) {
    if (!this.svgElement) return;
    const path = activeDocument.createElementNS("http://www.w3.org/2000/svg", "path");
    const displayFrom = this.toDisplayPosition(from);
    const displayTo = this.toDisplayPosition(to);
    const startX = displayFrom.x + _MindMapCanvas.NODE_WIDTH / 2;
    const startY = displayFrom.y + _MindMapCanvas.NODE_HEIGHT / 2;
    const endX = displayTo.x - _MindMapCanvas.NODE_WIDTH / 2;
    const endY = displayTo.y + _MindMapCanvas.NODE_HEIGHT / 2;
    const controlOffset = Math.max(60, Math.abs(endX - startX) / 2);
    const d = `M ${startX} ${startY} C ${startX + controlOffset} ${startY}, ${endX - controlOffset} ${endY}, ${endX} ${endY}`;
    path.setAttribute("d", d);
    path.setAttribute("fill", "none");
    path.setAttribute("stroke-width", "2");
    path.setAttribute("class", "mindmap-edge");
    this.svgElement.appendChild(path);
  }
  renderConnections(connections) {
    if (!this.svgElement) return;
    for (const connection of connections) {
      const from = this.positions.get(connection.fromNodeId);
      const to = this.positions.get(connection.toNodeId);
      if (!from || !to) continue;
      const path = this.createEdgePath(from, to);
      path.setAttribute("class", "mindmap-edge mindmap-cross-connection");
      this.svgElement.appendChild(path);
    }
  }
  createEdgePath(from, to) {
    const path = activeDocument.createElementNS("http://www.w3.org/2000/svg", "path");
    const displayFrom = this.toDisplayPosition(from);
    const displayTo = this.toDisplayPosition(to);
    const startX = displayFrom.x + _MindMapCanvas.NODE_WIDTH / 2;
    const startY = displayFrom.y + _MindMapCanvas.NODE_HEIGHT / 2;
    const endX = displayTo.x - _MindMapCanvas.NODE_WIDTH / 2;
    const endY = displayTo.y + _MindMapCanvas.NODE_HEIGHT / 2;
    const controlOffset = Math.max(60, Math.abs(endX - startX) / 2);
    const d = `M ${startX} ${startY} C ${startX + controlOffset} ${startY}, ${endX - controlOffset} ${endY}, ${endX} ${endY}`;
    path.setAttribute("d", d);
    path.setAttribute("fill", "none");
    path.setAttribute("stroke-width", "2");
    return path;
  }
  renderNodes(node, selectedNodeIds) {
    this.renderNode(node, selectedNodeIds.has(node.id));
    if (node.collapsed) return;
    for (const child of node.children) {
      this.renderNodes(child, selectedNodeIds);
    }
  }
  renderNode(node, isSelected) {
    if (!this.svgElement) return;
    const pos = this.positions.get(node.id);
    if (!pos) return;
    const g = activeDocument.createElementNS("http://www.w3.org/2000/svg", "g");
    g.setAttribute("data-node-id", node.id);
    g.setAttribute("class", "mindmap-node");
    this.setNodeTransform(g, pos);
    g.addEventListener("pointerdown", (event) => this.handleNodePointerDown(event, node.id));
    g.addEventListener("pointerup", (event) => this.handleNodePointerUp(event, node.id));
    g.addEventListener("contextmenu", (event) => this.handleNodeContextMenu(event, node.id));
    const rect = activeDocument.createElementNS("http://www.w3.org/2000/svg", "rect");
    rect.setAttribute("width", String(_MindMapCanvas.NODE_WIDTH));
    rect.setAttribute("height", String(_MindMapCanvas.NODE_HEIGHT));
    rect.setAttribute("rx", "8");
    rect.setAttribute("ry", "8");
    rect.setAttribute("class", this.getNodeClass(node, isSelected));
    g.appendChild(rect);
    if (node.children.length > 0 && node.id !== this.editingNodeId) {
      const toggle = activeDocument.createElementNS("http://www.w3.org/2000/svg", "g");
      toggle.setAttribute("class", "mindmap-node-action");
      toggle.setAttribute("data-node-action", "toggle");
      toggle.setAttribute("transform", "translate(12, 24)");
      const toggleCircle = activeDocument.createElementNS("http://www.w3.org/2000/svg", "circle");
      toggleCircle.setAttribute("r", "10");
      toggleCircle.setAttribute("class", "mindmap-node-action-circle");
      toggle.appendChild(toggleCircle);
      const toggleText = activeDocument.createElementNS("http://www.w3.org/2000/svg", "text");
      toggleText.setAttribute("text-anchor", "middle");
      toggleText.setAttribute("y", "4");
      toggleText.setAttribute("class", "mindmap-node-action-text");
      toggleText.textContent = node.collapsed ? "+" : "-";
      toggle.appendChild(toggleText);
      g.appendChild(toggle);
    }
    if (node.id === this.editingNodeId) {
      this.renderInlineEditor(g, node);
    } else {
      const text = activeDocument.createElementNS("http://www.w3.org/2000/svg", "text");
      text.setAttribute("x", String(_MindMapCanvas.NODE_WIDTH / 2));
      text.setAttribute("y", "29");
      text.setAttribute("text-anchor", "middle");
      text.setAttribute("class", "mindmap-node-label");
      text.textContent = this.truncate(node.content);
      g.appendChild(text);
    }
    if (node.children.length > 0) {
      const badge = activeDocument.createElementNS("http://www.w3.org/2000/svg", "text");
      badge.setAttribute("x", "30");
      badge.setAttribute("y", "43");
      badge.setAttribute("text-anchor", "middle");
      badge.setAttribute("class", "mindmap-node-count");
      badge.textContent = node.collapsed ? `+${node.children.length}` : String(node.children.length);
      g.appendChild(badge);
    }
    if (node.note) {
      const noteBadge = activeDocument.createElementNS("http://www.w3.org/2000/svg", "g");
      noteBadge.setAttribute("class", "mindmap-node-note-indicator");
      noteBadge.setAttribute("transform", "translate(0, 0)");
      const noteCircle = activeDocument.createElementNS("http://www.w3.org/2000/svg", "circle");
      noteCircle.setAttribute("cx", "0");
      noteCircle.setAttribute("cy", "0");
      noteCircle.setAttribute("r", "8");
      noteCircle.setAttribute("class", "mindmap-node-note-bubble");
      noteBadge.appendChild(noteCircle);
      const noteText = activeDocument.createElementNS("http://www.w3.org/2000/svg", "text");
      noteText.setAttribute("text-anchor", "middle");
      noteText.setAttribute("y", "4");
      noteText.setAttribute("class", "mindmap-node-note-text");
      noteText.textContent = "i";
      noteBadge.appendChild(noteText);
      g.appendChild(noteBadge);
    }
    const add = activeDocument.createElementNS("http://www.w3.org/2000/svg", "g");
    add.setAttribute("class", "mindmap-node-action");
    add.setAttribute("data-node-action", "add-child");
    add.setAttribute("transform", `translate(${_MindMapCanvas.NODE_WIDTH - 12}, 24)`);
    const addCircle = activeDocument.createElementNS("http://www.w3.org/2000/svg", "circle");
    addCircle.setAttribute("r", "10");
    addCircle.setAttribute("class", "mindmap-node-action-circle");
    add.appendChild(addCircle);
    const addText = activeDocument.createElementNS("http://www.w3.org/2000/svg", "text");
    addText.setAttribute("text-anchor", "middle");
    addText.setAttribute("y", "4");
    addText.setAttribute("class", "mindmap-node-action-text");
    addText.textContent = "+";
    add.appendChild(addText);
    g.appendChild(add);
    const remove = activeDocument.createElementNS("http://www.w3.org/2000/svg", "g");
    remove.setAttribute("class", "mindmap-node-action mindmap-node-action-danger");
    remove.setAttribute("data-node-action", "delete");
    remove.setAttribute("transform", `translate(${_MindMapCanvas.NODE_WIDTH - 12}, -2)`);
    const removeCircle = activeDocument.createElementNS("http://www.w3.org/2000/svg", "circle");
    removeCircle.setAttribute("r", "9");
    removeCircle.setAttribute("class", "mindmap-node-action-circle");
    remove.appendChild(removeCircle);
    const removeText = activeDocument.createElementNS("http://www.w3.org/2000/svg", "text");
    removeText.setAttribute("text-anchor", "middle");
    removeText.setAttribute("y", "4");
    removeText.setAttribute("class", "mindmap-node-action-text");
    removeText.textContent = "x";
    remove.appendChild(removeText);
    g.appendChild(remove);
    this.svgElement.appendChild(g);
    this.nodeElements.set(node.id, g);
  }
  renderInlineEditor(group, node) {
    const foreignObject = activeDocument.createElementNS("http://www.w3.org/2000/svg", "foreignObject");
    foreignObject.setAttribute("x", "14");
    foreignObject.setAttribute("y", "8");
    foreignObject.setAttribute("width", String(_MindMapCanvas.NODE_WIDTH - 28));
    foreignObject.setAttribute("height", String(_MindMapCanvas.NODE_HEIGHT - 16));
    const input = activeDocument.createElement("input");
    input.type = "text";
    input.value = node.content;
    input.className = "mindmap-inline-rename";
    input.addEventListener("pointerdown", (event) => event.stopPropagation());
    input.addEventListener("pointerup", (event) => event.stopPropagation());
    input.addEventListener("click", (event) => event.stopPropagation());
    input.addEventListener("dblclick", (event) => event.stopPropagation());
    let committed = false;
    const commit = (value) => {
      if (committed) return;
      committed = true;
      this.callbacks.onNodeRenameCommit(node.id, value);
    };
    input.addEventListener("keydown", (event) => {
      event.stopPropagation();
      if (event.key === "Enter") {
        event.preventDefault();
        commit(input.value);
      }
      if (event.key === "Escape") {
        event.preventDefault();
        commit(node.content);
      }
    });
    input.addEventListener("blur", () => commit(input.value));
    foreignObject.appendChild(input);
    group.appendChild(foreignObject);
    window.setTimeout(() => {
      input.focus();
      input.select();
    }, 0);
  }
  getNodeClass(node, isSelected) {
    const classes = ["mindmap-node-box"];
    if (isSelected) classes.push("is-selected");
    if (node.id === this.connectSourceId) classes.push("is-connecting");
    if (node.id === this.mergeSourceId) classes.push("is-merging");
    return classes.join(" ");
  }
  truncate(content) {
    return content.length > 22 ? `${content.slice(0, 19)}...` : content;
  }
  handleNodePointerDown(event, nodeId) {
    if (!this.svgElement) return;
    if (event.button === 2) {
      event.preventDefault();
      event.stopPropagation();
      this.openNodeContextMenu(nodeId, event);
      return;
    }
    if (event.button !== 0) {
      return;
    }
    event.stopPropagation();
    const action = this.getAction(event.target);
    if (action) {
      return;
    }
    const position = this.positions.get(nodeId);
    if (!position) return;
    const point = this.toSvgPoint(event.clientX, event.clientY);
    this.dragState = {
      nodeId,
      pointerId: event.pointerId,
      offsetX: point.x - (position.x + this.pan.x - _MindMapCanvas.NODE_WIDTH / 2),
      offsetY: point.y - (position.y + this.pan.y),
      moved: false
    };
    this.svgElement.setPointerCapture(event.pointerId);
  }
  handleSvgPointerDown(event) {
    if (!this.svgElement || event.button !== 0 || !event.shiftKey) return;
    if (event.target instanceof Element && event.target.closest("[data-node-id]")) return;
    event.preventDefault();
    const start = this.toSvgPoint(event.clientX, event.clientY);
    this.boxSelectState = {
      pointerId: event.pointerId,
      start,
      current: start,
      additive: true
    };
    this.svgElement.setPointerCapture(event.pointerId);
    this.renderSelectionBox();
  }
  handleNodeContextMenu(event, nodeId) {
    event.preventDefault();
    event.stopPropagation();
    this.openNodeContextMenu(nodeId, event);
  }
  handleSvgContextMenu(event) {
    const nodeId = this.getNodeIdFromTarget(event.target);
    if (!nodeId) return;
    event.preventDefault();
    event.stopPropagation();
    this.openNodeContextMenu(nodeId, event);
  }
  openNodeContextMenu(nodeId, event) {
    const now = Date.now();
    if (this.lastContextMenuNodeId === nodeId && now - this.lastContextMenuAt < 350) {
      return;
    }
    this.lastContextMenuNodeId = nodeId;
    this.lastContextMenuAt = now;
    this.dragState = null;
    this.boxSelectState = null;
    this.callbacks.onNodeContextMenu(nodeId, event);
  }
  handleNodePointerUp(event, nodeId) {
    const action = this.getAction(event.target);
    if (action === "add-child") {
      event.stopPropagation();
      this.callbacks.onNodeAddChild(nodeId);
      return;
    }
    if (action === "delete") {
      event.stopPropagation();
      this.callbacks.onNodeDelete(nodeId);
      return;
    }
    if (action === "toggle") {
      event.stopPropagation();
      this.callbacks.onNodeToggleCollapse(nodeId);
      return;
    }
  }
  handlePointerMove(event) {
    if (this.boxSelectState && this.boxSelectState.pointerId === event.pointerId) {
      event.preventDefault();
      this.boxSelectState.current = this.toSvgPoint(event.clientX, event.clientY);
      this.renderSelectionBox();
      return;
    }
    if (!this.dragState || this.dragState.pointerId !== event.pointerId) return;
    event.preventDefault();
    const point = this.toSvgPoint(event.clientX, event.clientY);
    const position = {
      x: point.x - this.dragState.offsetX + _MindMapCanvas.NODE_WIDTH / 2 - this.pan.x,
      y: point.y - this.dragState.offsetY - this.pan.y
    };
    this.positions.set(this.dragState.nodeId, position);
    this.dragState.moved = true;
    const element = this.nodeElements.get(this.dragState.nodeId);
    if (element) {
      this.setNodeTransform(element, position);
    }
  }
  handlePointerUp(event) {
    var _a, _b;
    if (this.boxSelectState && this.boxSelectState.pointerId === event.pointerId) {
      const state = this.boxSelectState;
      this.boxSelectState = null;
      if ((_a = this.svgElement) == null ? void 0 : _a.hasPointerCapture(event.pointerId)) {
        this.svgElement.releasePointerCapture(event.pointerId);
      }
      this.removeSelectionBox();
      this.callbacks.onBoxSelect(this.getNodesInBox(state), state.additive);
      return;
    }
    if (!this.dragState || this.dragState.pointerId !== event.pointerId) return;
    const dragState = this.dragState;
    this.dragState = null;
    if ((_b = this.svgElement) == null ? void 0 : _b.hasPointerCapture(event.pointerId)) {
      this.svgElement.releasePointerCapture(event.pointerId);
    }
    const position = this.positions.get(dragState.nodeId);
    if (!position) return;
    if (!dragState.moved) {
      this.activateNode(dragState.nodeId, event.shiftKey);
      return;
    }
    const targetNodeId = this.getDropTarget(event.clientX, event.clientY, dragState.nodeId);
    if (targetNodeId) {
      this.callbacks.onNodeDrop(dragState.nodeId, targetNodeId, position, event.shiftKey);
      return;
    }
    this.callbacks.onNodeMove(dragState.nodeId, position);
  }
  activateNode(nodeId, additive) {
    if (this.connectSourceId && this.connectSourceId !== nodeId) {
      this.resetClickState();
      this.callbacks.onNodeConnect(this.connectSourceId, nodeId);
      return;
    }
    if (this.mergeSourceId && this.mergeSourceId !== nodeId) {
      this.resetClickState();
      this.callbacks.onNodeMerge(this.mergeSourceId, nodeId);
      return;
    }
    const now = Date.now();
    if (this.lastClickNodeId === nodeId && now - this.lastClickAt <= 420) {
      this.resetClickState();
      this.callbacks.onNodeRename(nodeId);
      return;
    }
    this.lastClickNodeId = nodeId;
    this.lastClickAt = now;
    this.callbacks.onNodeSelect(nodeId, additive);
  }
  resetClickState() {
    this.lastClickNodeId = null;
    this.lastClickAt = 0;
  }
  getDropTarget(clientX, clientY, draggedNodeId) {
    var _a;
    for (const element of activeDocument.elementsFromPoint(clientX, clientY)) {
      const nodeElement = element.closest("[data-node-id]");
      const nodeId = (_a = nodeElement == null ? void 0 : nodeElement.getAttribute("data-node-id")) != null ? _a : null;
      if (nodeId && nodeId !== draggedNodeId) {
        return nodeId;
      }
    }
    return null;
  }
  getAction(target) {
    var _a;
    if (!(target instanceof Element)) return null;
    const actionElement = target.closest("[data-node-action]");
    return (_a = actionElement == null ? void 0 : actionElement.getAttribute("data-node-action")) != null ? _a : null;
  }
  getNodeIdFromTarget(target) {
    var _a, _b;
    if (!(target instanceof Element)) return null;
    return (_b = (_a = target.closest("[data-node-id]")) == null ? void 0 : _a.getAttribute("data-node-id")) != null ? _b : null;
  }
  toSvgPoint(clientX, clientY) {
    if (!this.svgElement) return { x: clientX, y: clientY };
    const point = this.svgElement.createSVGPoint();
    point.x = clientX;
    point.y = clientY;
    const matrix = this.svgElement.getScreenCTM();
    if (!matrix) return { x: clientX, y: clientY };
    const transformed = point.matrixTransform(matrix.inverse());
    return { x: transformed.x, y: transformed.y };
  }
  setNodeTransform(element, position) {
    const displayPosition = this.toDisplayPosition(position);
    element.setAttribute(
      "transform",
      `translate(${displayPosition.x - _MindMapCanvas.NODE_WIDTH / 2}, ${displayPosition.y})`
    );
  }
  renderSelectionBox() {
    if (!this.svgElement || !this.boxSelectState) return;
    let rect = this.svgElement.querySelector(".mindmap-selection-box");
    if (!rect) {
      rect = activeDocument.createElementNS("http://www.w3.org/2000/svg", "rect");
      rect.setAttribute("class", "mindmap-selection-box");
      this.svgElement.appendChild(rect);
    }
    const { start, current } = this.boxSelectState;
    const x = Math.min(start.x, current.x);
    const y = Math.min(start.y, current.y);
    const width = Math.abs(current.x - start.x);
    const height = Math.abs(current.y - start.y);
    rect.setAttribute("x", String(x));
    rect.setAttribute("y", String(y));
    rect.setAttribute("width", String(width));
    rect.setAttribute("height", String(height));
  }
  removeSelectionBox() {
    var _a, _b;
    (_b = (_a = this.svgElement) == null ? void 0 : _a.querySelector(".mindmap-selection-box")) == null ? void 0 : _b.remove();
  }
  getNodesInBox(state) {
    const left = Math.min(state.start.x, state.current.x) - this.pan.x;
    const right = Math.max(state.start.x, state.current.x) - this.pan.x;
    const top = Math.min(state.start.y, state.current.y) - this.pan.y;
    const bottom = Math.max(state.start.y, state.current.y) - this.pan.y;
    const selected = [];
    for (const [nodeId, position] of this.positions) {
      const nodeLeft = position.x - _MindMapCanvas.NODE_WIDTH / 2;
      const nodeRight = position.x + _MindMapCanvas.NODE_WIDTH / 2;
      const nodeTop = position.y;
      const nodeBottom = position.y + _MindMapCanvas.NODE_HEIGHT;
      if (nodeRight >= left && nodeLeft <= right && nodeBottom >= top && nodeTop <= bottom) {
        selected.push(nodeId);
      }
    }
    return selected;
  }
  toDisplayPosition(position) {
    return {
      x: position.x + this.pan.x,
      y: position.y + this.pan.y
    };
  }
  getContentBounds() {
    let maxX = 0;
    let maxY = 0;
    for (const pos of this.positions.values()) {
      maxX = Math.max(maxX, pos.x + _MindMapCanvas.NODE_WIDTH / 2);
      maxY = Math.max(maxY, pos.y + _MindMapCanvas.NODE_HEIGHT);
    }
    return {
      width: maxX + _MindMapCanvas.PADDING,
      height: maxY + _MindMapCanvas.PADDING
    };
  }
  getViewportSize() {
    return {
      width: this.container.clientWidth,
      height: this.container.clientHeight
    };
  }
  getSvgElement() {
    return this.svgElement;
  }
  centerNode(nodeId, zoom) {
    const center = this.getNodeContentCenter(nodeId, zoom);
    if (!center) return false;
    this.container.scrollLeft = Math.max(0, center.x - this.container.clientWidth / 2);
    this.container.scrollTop = Math.max(0, center.y - this.container.clientHeight / 2);
    return true;
  }
  getNodeContentCenter(nodeId, zoom) {
    const position = this.positions.get(nodeId);
    if (!position) return null;
    const displayPosition = this.toDisplayPosition(position);
    return {
      x: displayPosition.x * zoom,
      y: (displayPosition.y + _MindMapCanvas.NODE_HEIGHT / 2) * zoom
    };
  }
  clear() {
    if (this.svgElement) {
      this.svgElement.innerHTML = "";
    }
    this.nodeElements.clear();
    this.positions.clear();
    this.visibleNodes = [];
    this.dragState = null;
    this.boxSelectState = null;
    this.resetClickState();
  }
};
_MindMapCanvas.NODE_WIDTH = 160;
_MindMapCanvas.NODE_HEIGHT = 48;
_MindMapCanvas.PADDING = 72;
var MindMapCanvas = _MindMapCanvas;

// src/mindmap/tree.ts
function cloneMindMap(data) {
  return JSON.parse(JSON.stringify(data));
}
function createNode(content = "New node", position) {
  return {
    id: crypto.randomUUID(),
    content,
    children: [],
    position
  };
}
function findNode(node, id) {
  if (node.id === id) return node;
  for (const child of node.children) {
    const found = findNode(child, id);
    if (found) return found;
  }
  return null;
}
function findParent(node, childId) {
  for (const child of node.children) {
    if (child.id === childId) return node;
    const found = findParent(child, childId);
    if (found) return found;
  }
  return null;
}
function findChildRef(root, nodeId) {
  for (let index = 0; index < root.children.length; index++) {
    const child = root.children[index];
    if (child.id === nodeId) {
      return { parent: root, index };
    }
    const found = findChildRef(child, nodeId);
    if (found) return found;
  }
  return null;
}
function addChildNode(root, parentNodeId, node) {
  const parent = findNode(root, parentNodeId);
  if (!parent) return false;
  parent.children.push(node);
  return true;
}
function addSiblingNode(root, siblingNodeId, node) {
  const parent = findParent(root, siblingNodeId);
  if (!parent) return false;
  parent.children.push(node);
  return true;
}
function renameNode(root, nodeId, content) {
  const node = findNode(root, nodeId);
  const trimmed = content.trim();
  if (!node || !trimmed) return false;
  node.content = trimmed;
  return true;
}
function moveNode(root, nodeId, position) {
  const node = findNode(root, nodeId);
  if (!node) return false;
  node.position = position;
  return true;
}
function toggleCollapse(root, nodeId) {
  const node = findNode(root, nodeId);
  if (!node || node.children.length === 0) return false;
  node.collapsed = !node.collapsed;
  return true;
}
function deleteNode(root, nodeId) {
  const ref = findChildRef(root, nodeId);
  if (!ref) return null;
  const [removed] = ref.parent.children.splice(ref.index, 1);
  return removed != null ? removed : null;
}
function reparentNode(root, nodeId, targetNodeId, position) {
  if (nodeId === targetNodeId || isDescendant(root, nodeId, targetNodeId)) return false;
  const target = findNode(root, targetNodeId);
  if (!target) return false;
  const node = deleteNode(root, nodeId);
  if (!node) return false;
  node.position = position;
  target.children.push(node);
  return true;
}
function groupSiblingNodes(root, nodeIds, groupContent, position) {
  const refs = nodeIds.map((id) => ({ id, ref: findChildRef(root, id) })).filter((entry) => entry.ref !== null);
  if (refs.length < 2) return null;
  const parent = refs[0].ref.parent;
  if (!refs.every((entry) => entry.ref.parent === parent)) return null;
  const orderedRefs = refs.sort((a, b) => a.ref.index - b.ref.index);
  const orderedNodes = orderedRefs.map((entry) => parent.children[entry.ref.index]);
  const indices = orderedRefs.map((entry) => entry.ref.index).sort((a, b) => b - a);
  for (const index of indices) {
    parent.children.splice(index, 1);
  }
  const groupNode = {
    id: crypto.randomUUID(),
    content: groupContent.trim() || orderedNodes.map((node) => node.content).join(" + "),
    children: orderedNodes,
    collapsed: false,
    position
  };
  groupNode.children.forEach((node) => delete node.position);
  parent.children.splice(Math.min(...indices), 0, groupNode);
  return groupNode;
}
function isDescendant(root, nodeId, possibleDescendantId) {
  const node = findNode(root, nodeId);
  return node ? findNode(node, possibleDescendantId) !== null && node.id !== possibleDescendantId : false;
}
function clearPositions(node) {
  delete node.position;
  node.children.forEach(clearPositions);
}
function getGroupPosition(firstNode, secondNode) {
  var _a;
  if (!firstNode.position || !secondNode.position) return (_a = firstNode.position) != null ? _a : secondNode.position;
  return {
    x: (firstNode.position.x + secondNode.position.x) / 2,
    y: Math.min(firstNode.position.y, secondNode.position.y)
  };
}

// src/mindmap/history.ts
var CommandHistory = class {
  constructor() {
    this.undoStack = [];
    this.redoStack = [];
  }
  execute(label, data, mutate) {
    const before = cloneMindMap(data);
    const result = mutate();
    if (result === false) return null;
    const after = cloneMindMap(data);
    const command = { label, before, after };
    this.undoStack.push(command);
    if (this.undoStack.length > 100) {
      this.undoStack.shift();
    }
    this.redoStack = [];
    return command;
  }
  undo() {
    const command = this.undoStack.pop();
    if (!command) return null;
    this.redoStack.push(command);
    return cloneMindMap(command.before);
  }
  redo() {
    const command = this.redoStack.pop();
    if (!command) return null;
    this.undoStack.push(command);
    return cloneMindMap(command.after);
  }
  clear() {
    this.undoStack = [];
    this.redoStack = [];
  }
};

// src/mindmap/view.ts
var VIEW_TYPE = "obsidian-mindmap-view";
var MIN_ZOOM = 0.4;
var MAX_ZOOM = 2.5;
var ZOOM_STEP = 0.1;
var AUTOSAVE_DELAY_MS = 800;
var MindMapView = class _MindMapView extends import_obsidian2.ItemView {
  constructor(leaf) {
    super(leaf);
    this.data = null;
    this.canvas = null;
    this.state = {
      selectedNodeId: null,
      zoom: 1,
      pan: { x: 0, y: 0 }
    };
    this.file = null;
    this.connectSourceId = null;
    this.mergeSourceId = null;
    this.editingNodeId = null;
    this.panState = null;
    this.selectedNodeIds = /* @__PURE__ */ new Set();
    this.history = new CommandHistory();
    this.autosaveTimer = null;
    this.statusEl = null;
    this.minimapEl = null;
    this.isSpacePanPressed = false;
    this.connectButtonEl = null;
    this.mergeButtonEl = null;
  }
  getViewType() {
    return VIEW_TYPE;
  }
  getDisplayText() {
    return "Mind Map";
  }
  async onOpen() {
    this.containerEl.empty();
    this.containerEl.addClass("mindmap-container");
    const toolbar = this.containerEl.createDiv("mindmap-toolbar");
    toolbar.createEl("button", { text: "Zoom -" }, (button) => {
      button.addEventListener("click", () => this.adjustZoom(-ZOOM_STEP));
    });
    toolbar.createEl("button", { text: "Zoom +" }, (button) => {
      button.addEventListener("click", () => this.adjustZoom(ZOOM_STEP));
    });
    toolbar.createEl("button", { text: "100%" }, (button) => {
      button.addEventListener("click", () => this.setZoom(1));
    });
    toolbar.createEl("button", { text: "Fit" }, (button) => {
      button.addEventListener("click", () => this.fitToView());
    });
    toolbar.createEl("button", { text: "Undo" }, (button) => {
      button.addEventListener("click", () => this.undo());
    });
    toolbar.createEl("button", { text: "Redo" }, (button) => {
      button.addEventListener("click", () => this.redo());
    });
    toolbar.createEl("button", { text: "Add child" }, (button) => {
      button.addEventListener("click", () => this.addChildNode());
    });
    toolbar.createEl("button", { text: "Add sibling" }, (button) => {
      button.addEventListener("click", () => this.addSiblingNode());
    });
    toolbar.createEl("button", { text: "Rename" }, (button) => {
      button.addEventListener("click", () => this.renameNode());
    });
    toolbar.createEl("button", { text: "Connect" }, (button) => {
      this.connectButtonEl = button;
      button.addEventListener("click", () => this.startConnect());
    });
    toolbar.createEl("button", { text: "Merge" }, (button) => {
      this.mergeButtonEl = button;
      button.addEventListener("click", () => this.startMerge());
    });
    toolbar.createEl("button", { text: "Group" }, (button) => {
      button.addEventListener("click", () => this.groupSelectedNodes());
    });
    toolbar.createEl("button", { text: "Auto layout" }, (button) => {
      button.addEventListener("click", () => this.autoLayout());
    });
    toolbar.createEl("button", { text: "Delete" }, (button) => {
      button.addEventListener("click", () => this.deleteNode());
    });
    toolbar.createEl("button", { text: "Save" }, (button) => {
      button.addEventListener("click", () => {
        void this.save(true);
      });
    });
    toolbar.createEl("button", { text: "Download" }, (button) => {
      button.addEventListener("click", (event) => this.openDownloadMenu(event));
    });
    toolbar.createEl("button", { text: "Guide" }, (button) => {
      button.addEventListener("click", () => this.openGuide());
    });
    this.statusEl = toolbar.createSpan("mindmap-mode-status");
    const canvasContainer = this.containerEl.createDiv("mindmap-canvas");
    canvasContainer.tabIndex = 0;
    canvasContainer.addEventListener("mousedown", () => {
      canvasContainer.focus();
    });
    this.setupCanvasPanning(canvasContainer);
    canvasContainer.addEventListener("wheel", (event) => {
      event.preventDefault();
      this.adjustZoom(event.deltaY > 0 ? -ZOOM_STEP : ZOOM_STEP);
    }, { passive: false });
    this.minimapEl = canvasContainer.createDiv("mindmap-minimap");
    this.canvas = new MindMapCanvas(canvasContainer, {
      onNodeSelect: (nodeId, additive) => {
        this.selectNode(nodeId, additive);
        this.render();
      },
      onBoxSelect: (nodeIds, additive) => {
        this.selectNodes(nodeIds, additive);
        this.render();
      },
      onNodeRename: (nodeId) => {
        this.renameNode(nodeId);
      },
      onNodeRenameCommit: (nodeId, content) => {
        this.commitInlineRename(nodeId, content);
      },
      onNodeContextMenu: (nodeId, event) => {
        this.openNodeMenu(nodeId, event);
      },
      onNodeAddChild: (nodeId) => {
        this.addChildNode(nodeId);
      },
      onNodeDelete: (nodeId) => {
        this.deleteNode(nodeId);
      },
      onNodeToggleCollapse: (nodeId) => {
        this.toggleCollapse(nodeId);
      },
      onNodeMove: (nodeId, position) => {
        this.moveNode(nodeId, position);
      },
      onNodeDrop: (nodeId, targetNodeId, position, merge) => {
        this.dropNode(nodeId, targetNodeId, position, merge);
      },
      onNodeConnect: (fromNodeId, toNodeId) => {
        this.connectNodes(fromNodeId, toNodeId);
      },
      onNodeMerge: (sourceNodeId, targetNodeId) => {
        this.mergeNodes(sourceNodeId, targetNodeId);
      }
    });
    this.setupSpacePanHandlers();
    this.setupGlobalHotkeys();
    this.updateStatus();
    if (this.data) {
      this.render();
    } else {
      this.createNew();
    }
  }
  async onClose() {
    var _a;
    if (this.autosaveTimer !== null) {
      window.clearTimeout(this.autosaveTimer);
      this.autosaveTimer = null;
    }
    if (this.data) {
      await this.save(false);
    }
    (_a = this.canvas) == null ? void 0 : _a.clear();
    this.minimapEl = null;
  }
  getState() {
    var _a, _b;
    return {
      ...super.getState(),
      filePath: (_b = (_a = this.file) == null ? void 0 : _a.path) != null ? _b : null,
      data: this.data,
      view: this.state
    };
  }
  async setState(state, result) {
    var _a, _b, _c, _d, _e, _f;
    await super.setState(state, result);
    const savedState = this.parseSavedState(state);
    if (savedState.filePath) {
      await this.loadFile(savedState.filePath);
      return;
    }
    if (savedState.data) {
      this.data = savedState.data;
      this.file = null;
      this.state = (_e = savedState.view) != null ? _e : {
        selectedNodeId: this.data.root.id,
        zoom: (_b = (_a = this.data.view) == null ? void 0 : _a.zoom) != null ? _b : 1,
        pan: (_d = (_c = this.data.view) == null ? void 0 : _c.pan) != null ? _d : { x: 0, y: 0 }
      };
      this.selectedNodeIds = /* @__PURE__ */ new Set([(_f = this.state.selectedNodeId) != null ? _f : this.data.root.id]);
      this.connectSourceId = null;
      this.mergeSourceId = null;
      this.editingNodeId = null;
      this.history.clear();
      this.render();
    }
  }
  parseSavedState(state) {
    if (!state || typeof state !== "object") return {};
    const record = state;
    return {
      filePath: typeof record.filePath === "string" ? record.filePath : null,
      data: this.isMindMapData(record.data) ? record.data : null,
      view: this.isMindMapViewState(record.view) ? record.view : void 0
    };
  }
  isMindMapData(value) {
    if (!value || typeof value !== "object") return false;
    const record = value;
    const root = record.root;
    return typeof record.version === "string" && !!root && typeof root.id === "string" && typeof root.content === "string" && Array.isArray(root.children);
  }
  isMindMapViewState(value) {
    if (!value || typeof value !== "object") return false;
    const record = value;
    const pan = record.pan;
    return (typeof record.selectedNodeId === "string" || record.selectedNodeId === null) && typeof record.zoom === "number" && !!pan && typeof pan.x === "number" && typeof pan.y === "number";
  }
  async loadFile(path) {
    var _a, _b, _c, _d;
    const file = this.app.vault.getAbstractFileByPath(path);
    if (file instanceof import_obsidian2.TFile) {
      this.file = file;
    }
    try {
      const content = await this.app.vault.adapter.read(path);
      const parsed = parseMindMap(content);
      if (parsed) {
        this.data = parsed;
      } else {
        this.data = createEmptyMindMap();
      }
    } catch (error) {
      console.error("Failed to load mind map:", error);
      this.data = createEmptyMindMap();
    }
    this.state.selectedNodeId = this.data.root.id;
    this.state.zoom = (_b = (_a = this.data.view) == null ? void 0 : _a.zoom) != null ? _b : 1;
    this.state.pan = (_d = (_c = this.data.view) == null ? void 0 : _c.pan) != null ? _d : { x: 0, y: 0 };
    this.selectedNodeIds = /* @__PURE__ */ new Set([this.data.root.id]);
    this.connectSourceId = null;
    this.mergeSourceId = null;
    this.editingNodeId = null;
    this.history.clear();
    this.render();
  }
  createNew() {
    var _a, _b, _c, _d;
    this.data = createEmptyMindMap();
    this.file = null;
    this.state.selectedNodeId = this.data.root.id;
    this.state.zoom = (_b = (_a = this.data.view) == null ? void 0 : _a.zoom) != null ? _b : 1;
    this.state.pan = (_d = (_c = this.data.view) == null ? void 0 : _c.pan) != null ? _d : { x: 0, y: 0 };
    this.selectedNodeIds = /* @__PURE__ */ new Set([this.data.root.id]);
    this.connectSourceId = null;
    this.mergeSourceId = null;
    this.editingNodeId = null;
    this.history.clear();
    this.render();
  }
  render() {
    var _a;
    if (!this.data || !this.canvas) return;
    this.canvas.render(
      this.data.root,
      (_a = this.data.connections) != null ? _a : [],
      Array.from(this.selectedNodeIds),
      this.connectSourceId,
      this.mergeSourceId,
      this.editingNodeId,
      this.state.zoom,
      this.state.pan
    );
    this.renderMinimap();
    this.updateStatus();
  }
  adjustZoom(delta) {
    this.setZoom(Number((this.state.zoom + delta).toFixed(2)));
  }
  setZoom(zoom) {
    var _a, _b, _c;
    const oldZoom = this.state.zoom;
    const newZoom = Math.min(MAX_ZOOM, Math.max(MIN_ZOOM, Number(zoom.toFixed(2))));
    if (newZoom === oldZoom) return;
    const focusNodeId = (_c = (_b = this.state.selectedNodeId) != null ? _b : (_a = this.data) == null ? void 0 : _a.root.id) != null ? _c : null;
    this.state.zoom = newZoom;
    this.updatePersistedViewState();
    this.render();
    if (focusNodeId && this.canvas) {
      this.canvas.centerNode(focusNodeId, newZoom);
    }
    this.scheduleAutosave();
  }
  selectNode(nodeId, additive) {
    if (additive) {
      if (this.selectedNodeIds.has(nodeId)) {
        this.selectedNodeIds.delete(nodeId);
      } else {
        this.selectedNodeIds.add(nodeId);
      }
      if (this.selectedNodeIds.size === 0) {
        this.selectedNodeIds.add(nodeId);
      }
    } else {
      this.selectedNodeIds = /* @__PURE__ */ new Set([nodeId]);
    }
    this.state.selectedNodeId = nodeId;
    this.connectSourceId = null;
    this.mergeSourceId = null;
    this.editingNodeId = null;
  }
  selectNodes(nodeIds, additive) {
    if (nodeIds.length === 0) return;
    if (additive) {
      for (const nodeId of nodeIds) {
        this.selectedNodeIds.add(nodeId);
      }
    } else {
      this.selectedNodeIds = new Set(nodeIds);
    }
    this.state.selectedNodeId = nodeIds[nodeIds.length - 1];
    this.connectSourceId = null;
    this.mergeSourceId = null;
    this.editingNodeId = null;
  }
  runCommand(label, mutate) {
    if (!this.data) return false;
    const command = this.history.execute(label, this.data, mutate);
    if (!command) return false;
    this.render();
    this.scheduleAutosave();
    return true;
  }
  undo() {
    var _a, _b, _c, _d;
    const previous = this.history.undo();
    if (!previous) return;
    this.data = previous;
    this.state.selectedNodeId = this.data.root.id;
    this.state.zoom = (_b = (_a = this.data.view) == null ? void 0 : _a.zoom) != null ? _b : this.state.zoom;
    this.state.pan = (_d = (_c = this.data.view) == null ? void 0 : _c.pan) != null ? _d : this.state.pan;
    this.selectedNodeIds = /* @__PURE__ */ new Set([this.data.root.id]);
    this.connectSourceId = null;
    this.mergeSourceId = null;
    this.editingNodeId = null;
    this.render();
    this.scheduleAutosave();
  }
  redo() {
    var _a, _b, _c, _d;
    const next = this.history.redo();
    if (!next) return;
    this.data = next;
    this.state.selectedNodeId = this.data.root.id;
    this.state.zoom = (_b = (_a = this.data.view) == null ? void 0 : _a.zoom) != null ? _b : this.state.zoom;
    this.state.pan = (_d = (_c = this.data.view) == null ? void 0 : _c.pan) != null ? _d : this.state.pan;
    this.selectedNodeIds = /* @__PURE__ */ new Set([this.data.root.id]);
    this.connectSourceId = null;
    this.mergeSourceId = null;
    this.editingNodeId = null;
    this.render();
    this.scheduleAutosave();
  }
  scheduleAutosave() {
    if (this.autosaveTimer !== null) {
      window.clearTimeout(this.autosaveTimer);
    }
    this.autosaveTimer = window.setTimeout(() => {
      this.autosaveTimer = null;
      void this.save(false);
    }, AUTOSAVE_DELAY_MS);
  }
  fitToView() {
    if (!this.canvas) return;
    const bounds = this.canvas.getContentBounds();
    const viewport = this.canvas.getViewportSize();
    if (bounds.width <= 0 || bounds.height <= 0) return;
    const zoom = Math.min(
      MAX_ZOOM,
      Math.max(MIN_ZOOM, Math.min(viewport.width / bounds.width, viewport.height / bounds.height) * 0.9)
    );
    this.state.zoom = Number(zoom.toFixed(2));
    this.state.pan = {
      x: Math.max(0, (viewport.width / this.state.zoom - bounds.width) / 2),
      y: Math.max(0, (viewport.height / this.state.zoom - bounds.height) / 2)
    };
    this.updatePersistedViewState();
    this.render();
    this.scheduleAutosave();
  }
  updateStatus() {
    var _a, _b;
    if (!this.statusEl) return;
    const mode = this.connectSourceId ? "Connect: click target" : this.mergeSourceId ? "Merge: click sibling target" : `${this.selectedNodeIds.size} selected`;
    const zoom = `${Math.round(this.state.zoom * 100)}%`;
    this.statusEl.setText(`${mode} \xB7 Zoom ${zoom}`);
    (_a = this.connectButtonEl) == null ? void 0 : _a.toggleClass("is-active", this.connectSourceId !== null);
    (_b = this.mergeButtonEl) == null ? void 0 : _b.toggleClass("is-active", this.mergeSourceId !== null);
  }
  setupCanvasPanning(canvasContainer) {
    canvasContainer.addEventListener("pointerdown", (event) => {
      const isMiddlePan = event.button === 1;
      const isCanvasPan = event.button === 0 && !event.shiftKey && !this.isNodeEventTarget(event.target);
      const isSpacePan = event.button === 0 && this.isSpacePanPressed;
      if (!isMiddlePan && !isCanvasPan && !isSpacePan) return;
      event.preventDefault();
      canvasContainer.focus();
      canvasContainer.classList.add("is-panning");
      this.panState = {
        pointerId: event.pointerId,
        startX: event.clientX,
        startY: event.clientY,
        startPanX: this.state.pan.x,
        startPanY: this.state.pan.y
      };
      canvasContainer.setPointerCapture(event.pointerId);
    });
    canvasContainer.addEventListener("pointermove", (event) => {
      if (!this.panState || this.panState.pointerId !== event.pointerId) return;
      event.preventDefault();
      this.state.pan = {
        x: this.panState.startPanX + event.clientX - this.panState.startX,
        y: this.panState.startPanY + event.clientY - this.panState.startY
      };
      this.updatePersistedViewState();
      this.render();
    });
    const stopPanning = (event) => {
      if (!this.panState || this.panState.pointerId !== event.pointerId) return;
      if (canvasContainer.hasPointerCapture(event.pointerId)) {
        canvasContainer.releasePointerCapture(event.pointerId);
      }
      canvasContainer.classList.remove("is-panning");
      this.panState = null;
      this.scheduleAutosave();
    };
    canvasContainer.addEventListener("pointerup", stopPanning);
    canvasContainer.addEventListener("pointercancel", stopPanning);
  }
  isNodeEventTarget(target) {
    return target instanceof Element && target.closest("[data-node-id]") !== null;
  }
  async save(showNotice = false) {
    var _a;
    if (!this.data) {
      if (showNotice) new import_obsidian2.Notice("Nothing to save.");
      return;
    }
    try {
      this.updatePersistedViewState();
      const filePath = (_a = this.file) == null ? void 0 : _a.path;
      if (filePath) {
        const existingContent = await this.app.vault.adapter.exists(filePath) ? await this.app.vault.adapter.read(filePath) : "";
        const content = serializeMindMap(this.data, existingContent);
        await this.app.vault.adapter.write(filePath, content);
      } else {
        const content = serializeMindMap(this.data);
        const newPath = await this.getNewFilePath();
        await this.app.vault.create(newPath, content);
        const newFile = this.app.vault.getAbstractFileByPath(newPath);
        if (newFile instanceof import_obsidian2.TFile) {
          this.file = newFile;
        }
      }
      if (showNotice) new import_obsidian2.Notice("Mind map saved.");
    } catch (error) {
      console.error("Failed to save mind map:", error);
      if (showNotice) new import_obsidian2.Notice(`Failed to save mind map: ${this.getErrorMessage(error)}`);
    }
  }
  updatePersistedViewState() {
    if (!this.data) return;
    this.data.view = {
      zoom: this.state.zoom,
      pan: { ...this.state.pan }
    };
  }
  async getNewFilePath() {
    var _a;
    const activeFile = this.app.workspace.getActiveFile();
    const fileName = `Mind map ${(/* @__PURE__ */ new Date()).toISOString().slice(0, 10)}`;
    const dir = (_a = activeFile == null ? void 0 : activeFile.parent) == null ? void 0 : _a.path;
    const basePath = (0, import_obsidian2.normalizePath)(dir ? `${dir}/${fileName}` : fileName);
    return this.getAvailableMarkdownPath(basePath);
  }
  async getAvailableMarkdownPath(basePath) {
    let index = 1;
    let candidate = `${basePath}.md`;
    while (await this.app.vault.adapter.exists(candidate)) {
      index += 1;
      candidate = `${basePath} ${index}.md`;
    }
    return candidate;
  }
  getErrorMessage(error) {
    if (error instanceof Error && error.message) return error.message;
    if (typeof error === "string") return error;
    return "unknown error";
  }
  setupGlobalHotkeys() {
    this.registerDomEvent(window, "keydown", (event) => {
      if (!this.isActiveMindMapView() || this.isTextInputTarget(event.target)) return;
      const handled = this.handleHotkey(event);
      if (handled) {
        event.preventDefault();
        event.stopPropagation();
      }
    });
  }
  handleHotkey(event) {
    var _a;
    const isMod = event.metaKey || event.ctrlKey;
    const key = event.key;
    if (isMod && !event.shiftKey && key.toLowerCase() === "z") {
      this.undo();
      return true;
    }
    if (isMod && event.shiftKey && key.toLowerCase() === "z") {
      this.redo();
      return true;
    }
    if (isMod && key.toLowerCase() === "s") {
      void this.save(true);
      return true;
    }
    if (isMod && key === "/") {
      this.openGuide();
      return true;
    }
    if (isMod && (key === "=" || key === "+") || key === "+") {
      this.adjustZoom(ZOOM_STEP);
      return true;
    }
    if (isMod && key === "-" || key === "-") {
      this.adjustZoom(-ZOOM_STEP);
      return true;
    }
    if (isMod && key === "0") {
      this.setZoom(1);
      return true;
    }
    if (key === "Tab") {
      this.addChildNode();
      return true;
    }
    if (key === "Enter") {
      this.addSiblingNode();
      return true;
    }
    if (key === "Backspace" || key === "Delete") {
      this.deleteNode();
      return true;
    }
    if (key === "F2") {
      this.renameNode();
      return true;
    }
    if (key === " ") {
      this.isSpacePanPressed = true;
      (_a = this.containerEl.querySelector(".mindmap-canvas")) == null ? void 0 : _a.addClass("is-space-pan");
      return true;
    }
    return false;
  }
  isActiveMindMapView() {
    return this.app.workspace.getActiveViewOfType(_MindMapView) === this;
  }
  isTextInputTarget(target) {
    if (!(target instanceof HTMLElement)) return false;
    return target.instanceOf(HTMLInputElement) || target.instanceOf(HTMLTextAreaElement) || target.isContentEditable;
  }
  openGuide() {
    new GuideModal(this.app).open();
  }
  openDownloadMenu(event) {
    const menu = new import_obsidian2.Menu();
    for (const [format, label] of [
      ["png", "Download PNG"],
      ["jpeg", "Download JPEG"],
      ["pdf", "Download PDF"]
    ]) {
      menu.addItem((item) => {
        item.setTitle(label).setIcon("download").onClick(() => {
          void this.downloadMindMap(format);
        });
      });
    }
    menu.showAtMouseEvent(event);
  }
  async downloadMindMap(format) {
    try {
      const name = this.getDownloadBaseName();
      if (format === "pdf") {
        const image = await this.renderMindMapImage("image/jpeg");
        this.downloadBlob(this.createPdfFromJpeg(image.dataUrl, image.width, image.height), `${name}.pdf`);
      } else {
        const mime = format === "png" ? "image/png" : "image/jpeg";
        const image = await this.renderMindMapImage(mime);
        this.downloadBlob(image.blob, `${name}.${format === "png" ? "png" : "jpg"}`);
      }
      new import_obsidian2.Notice(`Mind map downloaded as ${format.toUpperCase()}.`);
    } catch (error) {
      console.error("Failed to download mind map:", error);
      new import_obsidian2.Notice(`Failed to download mind map: ${this.getErrorMessage(error)}`);
    }
  }
  async renderMindMapImage(mime) {
    const exportSvg = this.getExportSvg();
    const url = URL.createObjectURL(new Blob([exportSvg.svg], { type: "image/svg+xml;charset=utf-8" }));
    try {
      const image = await new Promise((resolve, reject) => {
        const img = new Image();
        img.onload = () => resolve(img);
        img.onerror = () => reject(new Error("Could not render SVG export."));
        img.src = url;
      });
      const scale = 2;
      const canvas = activeDocument.createElement("canvas");
      canvas.width = exportSvg.width * scale;
      canvas.height = exportSvg.height * scale;
      const context = canvas.getContext("2d");
      if (!context) throw new Error("Canvas export is not available.");
      context.fillStyle = exportSvg.background;
      context.fillRect(0, 0, canvas.width, canvas.height);
      context.drawImage(image, 0, 0, canvas.width, canvas.height);
      const dataUrl = canvas.toDataURL(mime, 0.92);
      const blob = await new Promise((resolve, reject) => {
        canvas.toBlob((result) => result ? resolve(result) : reject(new Error("Could not create image export.")), mime, 0.92);
      });
      return { blob, dataUrl, width: canvas.width, height: canvas.height };
    } finally {
      URL.revokeObjectURL(url);
    }
  }
  getExportSvg() {
    var _a;
    const source = (_a = this.canvas) == null ? void 0 : _a.getSvgElement();
    if (!source) throw new Error("No mind map canvas to export.");
    const clone = source.cloneNode(true);
    const [width, height] = this.getSvgSize(source);
    const background = getComputedStyle(this.containerEl).getPropertyValue("--background-primary").trim() || "#ffffff";
    clone.setAttribute("xmlns", "http://www.w3.org/2000/svg");
    clone.setAttribute("width", String(width));
    clone.setAttribute("height", String(height));
    this.inlineSvgStyles(source, clone);
    const backgroundRect = activeDocument.createElementNS("http://www.w3.org/2000/svg", "rect");
    backgroundRect.setAttribute("width", String(width));
    backgroundRect.setAttribute("height", String(height));
    backgroundRect.setAttribute("fill", background);
    clone.insertBefore(backgroundRect, clone.firstChild);
    return { svg: new XMLSerializer().serializeToString(clone), width, height, background };
  }
  getSvgSize(svg) {
    var _a;
    const viewBox = (_a = svg.getAttribute("viewBox")) == null ? void 0 : _a.split(/\s+/).map(Number);
    if (viewBox && viewBox.length === 4 && viewBox.every(Number.isFinite)) {
      return [Math.ceil(viewBox[2]), Math.ceil(viewBox[3])];
    }
    return [Math.ceil(svg.clientWidth), Math.ceil(svg.clientHeight)];
  }
  inlineSvgStyles(source, clone) {
    const computed = getComputedStyle(source);
    const properties = [
      "fill",
      "stroke",
      "stroke-width",
      "stroke-dasharray",
      "opacity",
      "font-family",
      "font-size",
      "font-weight",
      "text-anchor",
      "filter"
    ];
    clone.setAttribute("style", properties.map((property) => `${property}:${computed.getPropertyValue(property)}`).join(";"));
    Array.from(source.children).forEach((child, index) => {
      const cloneChild = clone.children.item(index);
      if (cloneChild) this.inlineSvgStyles(child, cloneChild);
    });
  }
  createPdfFromJpeg(dataUrl, width, height) {
    var _a;
    const image = this.base64ToBytes((_a = dataUrl.split(",")[1]) != null ? _a : "");
    const pageWidth = width * 0.75;
    const pageHeight = height * 0.75;
    const content = `q
${pageWidth} 0 0 ${pageHeight} 0 0 cm
/Im0 Do
Q
`;
    const encoder = new TextEncoder();
    const chunks = [];
    const offsets = [0];
    let offset = 0;
    const add = (chunk) => {
      const bytes = typeof chunk === "string" ? encoder.encode(chunk) : chunk;
      chunks.push(Uint8Array.from(bytes).buffer);
      offset += bytes.length;
    };
    const object = (number, body) => {
      offsets[number] = offset;
      add(`${number} 0 obj
${body}
endobj
`);
    };
    add("%PDF-1.4\n");
    object(1, "<< /Type /Catalog /Pages 2 0 R >>");
    object(2, "<< /Type /Pages /Kids [3 0 R] /Count 1 >>");
    object(3, `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pageWidth} ${pageHeight}] /Resources << /XObject << /Im0 4 0 R >> >> /Contents 5 0 R >>`);
    offsets[4] = offset;
    add(`4 0 obj
<< /Type /XObject /Subtype /Image /Width ${width} /Height ${height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${image.length} >>
stream
`);
    add(image);
    add("\nendstream\nendobj\n");
    object(5, `<< /Length ${encoder.encode(content).length} >>
stream
${content}endstream`);
    const xref = offset;
    add(`xref
0 6
0000000000 65535 f 
${offsets.slice(1).map((entry) => `${`0000000000${entry}`.slice(-10)} 00000 n `).join("\n")}
trailer
<< /Size 6 /Root 1 0 R >>
startxref
${xref}
%%EOF
`);
    return new Blob(chunks, { type: "application/pdf" });
  }
  base64ToBytes(base64) {
    const binary = atob(base64);
    const bytes = new Uint8Array(binary.length);
    for (let index = 0; index < binary.length; index++) {
      bytes[index] = binary.charCodeAt(index);
    }
    return bytes;
  }
  downloadBlob(blob, filename) {
    const url = URL.createObjectURL(blob);
    const link = activeDocument.createElement("a");
    link.href = url;
    link.download = filename;
    link.click();
    URL.revokeObjectURL(url);
  }
  getDownloadBaseName() {
    var _a, _b, _c;
    const name = ((_c = (_b = (_a = this.file) == null ? void 0 : _a.path) == null ? void 0 : _b.split("/").pop()) == null ? void 0 : _c.replace(/\.md$/i, "")) || "mind-map";
    return [...name].map((character) => '<>:"/\\|?*'.includes(character) || character.charCodeAt(0) < 32 ? "-" : character).join("").trim() || "mind-map";
  }
  openNodeMenu(nodeId, event) {
    if (!this.data) return;
    const node = findNode(this.data.root, nodeId);
    if (!node) return;
    this.selectNode(nodeId, false);
    this.render();
    const menu = new import_obsidian2.Menu();
    menu.addItem((item) => {
      item.setTitle("Edit label").setIcon("pencil").onClick(() => this.renameNode(nodeId));
    });
    menu.addItem((item) => {
      item.setTitle(node.note ? "Edit note" : "Add note").setIcon("sticky-note").onClick(() => this.editNodeNote(nodeId));
    });
    menu.addItem((item) => {
      item.setTitle(node.linkedFilePath ? "Open linked note" : "New linked note").setIcon("file-text").onClick(() => {
        void this.openOrCreateLinkedNote(nodeId);
      });
    });
    if (node.linkedFilePath) {
      menu.addItem((item) => {
        item.setTitle("Remove linked note").setIcon("unlink").onClick(() => this.clearLinkedNote(nodeId));
      });
    }
    menu.addSeparator();
    menu.addItem((item) => {
      item.setTitle("Delete").setIcon("trash").onClick(() => this.deleteNode(nodeId));
    });
    menu.showAtMouseEvent(event);
  }
  editNodeNote(nodeId) {
    var _a;
    if (!this.data) return;
    const node = findNode(this.data.root, nodeId);
    if (!node) return;
    new NodeNoteModal(this.app, node.content, (_a = node.note) != null ? _a : "", (note) => {
      this.runCommand("Edit node note", () => {
        if (!this.data) return false;
        const current = findNode(this.data.root, nodeId);
        if (!current) return false;
        const trimmed = note.trim();
        if (trimmed) {
          current.note = trimmed;
        } else {
          delete current.note;
        }
        this.state.selectedNodeId = nodeId;
        this.selectedNodeIds = /* @__PURE__ */ new Set([nodeId]);
        this.connectSourceId = null;
        this.mergeSourceId = null;
        this.editingNodeId = null;
      });
    }).open();
  }
  async openOrCreateLinkedNote(nodeId) {
    if (!this.data) return;
    const node = findNode(this.data.root, nodeId);
    if (!node) return;
    if (node.linkedFilePath) {
      await this.openLinkedFile(node.linkedFilePath);
      return;
    }
    const filePath = await this.createLinkedNoteFile(node);
    this.runCommand("Link node note", () => {
      if (!this.data) return false;
      const current = findNode(this.data.root, nodeId);
      if (!current) return false;
      current.linkedFilePath = filePath;
      this.state.selectedNodeId = nodeId;
      this.selectedNodeIds = /* @__PURE__ */ new Set([nodeId]);
      this.connectSourceId = null;
      this.mergeSourceId = null;
      this.editingNodeId = null;
    });
    await this.openLinkedFile(filePath);
  }
  async createLinkedNoteFile(node) {
    var _a;
    const activeFile = this.file || this.app.workspace.getActiveFile();
    const dir = activeFile instanceof import_obsidian2.TFile ? (_a = activeFile.parent) == null ? void 0 : _a.path : void 0;
    const baseName = this.slugifyFileName(node.content || "Node note");
    const basePath = (0, import_obsidian2.normalizePath)(dir ? `${dir}/${baseName}` : baseName);
    const filePath = await this.getAvailableMarkdownPath(basePath);
    const body = [
      `# ${node.content}`,
      "",
      node.note ? node.note : ""
    ].join("\n");
    await this.app.vault.create(filePath, body);
    return filePath;
  }
  async openLinkedFile(filePath) {
    const file = this.app.vault.getAbstractFileByPath(filePath);
    if (file instanceof import_obsidian2.TFile) {
      await this.app.workspace.getLeaf("tab").openFile(file);
    } else {
      new import_obsidian2.Notice(`Linked note not found: ${filePath}`);
    }
  }
  clearLinkedNote(nodeId) {
    this.runCommand("Remove linked note", () => {
      if (!this.data) return false;
      const node = findNode(this.data.root, nodeId);
      if (!node || !node.linkedFilePath) return false;
      delete node.linkedFilePath;
      this.state.selectedNodeId = nodeId;
      this.selectedNodeIds = /* @__PURE__ */ new Set([nodeId]);
    });
  }
  slugifyFileName(text) {
    const slug = text.trim().replace(/[\\/:*?"<>|#^[\]]+/g, " ").replace(/\s+/g, " ").slice(0, 80).trim();
    return slug || "Node note";
  }
  addChildNode(parentNodeId = this.state.selectedNodeId) {
    if (!this.data || !parentNodeId) {
      new import_obsidian2.Notice("Select a node before adding a child.");
      return;
    }
    const parent = findNode(this.data.root, parentNodeId);
    if (!parent) {
      new import_obsidian2.Notice("Selected node was not found.");
      return;
    }
    const newNode = createNode("New node", this.getChildPosition(parent));
    this.runCommand("Add child", () => {
      if (!this.data) return false;
      if (!addChildNode(this.data.root, parentNodeId, newNode)) return false;
      this.state.selectedNodeId = newNode.id;
      this.selectedNodeIds = /* @__PURE__ */ new Set([newNode.id]);
      this.connectSourceId = null;
      this.mergeSourceId = null;
      this.editingNodeId = newNode.id;
    });
  }
  addSiblingNode() {
    if (!this.data || !this.state.selectedNodeId) {
      new import_obsidian2.Notice("Select a node before adding a sibling.");
      return;
    }
    if (this.state.selectedNodeId === this.data.root.id) {
      new import_obsidian2.Notice("The central node cannot have a sibling. Add a child instead.");
      return;
    }
    const newNode = createNode("New node", this.getSiblingPosition(this.state.selectedNodeId));
    this.runCommand("Add sibling", () => {
      if (!this.data || !this.state.selectedNodeId) return false;
      if (!addSiblingNode(this.data.root, this.state.selectedNodeId, newNode)) return false;
      this.state.selectedNodeId = newNode.id;
      this.selectedNodeIds = /* @__PURE__ */ new Set([newNode.id]);
      this.connectSourceId = null;
      this.mergeSourceId = null;
      this.editingNodeId = newNode.id;
    });
  }
  renameNode(nodeId = this.state.selectedNodeId) {
    if (!this.data || !nodeId) {
      new import_obsidian2.Notice("Select a node to rename.");
      return;
    }
    const node = findNode(this.data.root, nodeId);
    if (!node) {
      new import_obsidian2.Notice("Selected node was not found.");
      return;
    }
    this.state.selectedNodeId = node.id;
    this.selectedNodeIds = /* @__PURE__ */ new Set([node.id]);
    this.connectSourceId = null;
    this.mergeSourceId = null;
    this.editingNodeId = node.id;
    this.render();
  }
  commitInlineRename(nodeId, content) {
    if (!this.data) return;
    const node = findNode(this.data.root, nodeId);
    const trimmed = content.trim();
    this.editingNodeId = null;
    if (!node || !trimmed || trimmed === node.content) {
      this.render();
      return;
    }
    this.runCommand("Rename node", () => {
      if (!this.data) return false;
      if (!renameNode(this.data.root, nodeId, trimmed)) return false;
      this.state.selectedNodeId = nodeId;
      this.selectedNodeIds = /* @__PURE__ */ new Set([nodeId]);
      this.connectSourceId = null;
      this.mergeSourceId = null;
    });
  }
  startConnect() {
    if (!this.data || !this.state.selectedNodeId) {
      new import_obsidian2.Notice("Select a source node first.");
      return;
    }
    if (this.connectSourceId === this.state.selectedNodeId) {
      this.connectSourceId = null;
      this.render();
      return;
    }
    this.connectSourceId = this.state.selectedNodeId;
    this.mergeSourceId = null;
    this.editingNodeId = null;
    this.render();
  }
  startMerge() {
    if (!this.data || !this.state.selectedNodeId) {
      new import_obsidian2.Notice("Select a source node first.");
      return;
    }
    if (this.state.selectedNodeId === this.data.root.id) {
      new import_obsidian2.Notice("The central node cannot be merged. Merge sibling child nodes instead.");
      return;
    }
    if (this.mergeSourceId === this.state.selectedNodeId) {
      this.mergeSourceId = null;
      this.render();
      return;
    }
    this.mergeSourceId = this.state.selectedNodeId;
    this.connectSourceId = null;
    this.editingNodeId = null;
    this.render();
  }
  groupSelectedNodes() {
    if (!this.data || this.selectedNodeIds.size < 2) {
      new import_obsidian2.Notice("Select at least two sibling nodes to group.");
      return;
    }
    const refs = Array.from(this.selectedNodeIds).map((id) => ({ id, ref: findChildRef(this.data.root, id) })).filter((entry) => entry.ref !== null);
    if (refs.length < 2) {
      new import_obsidian2.Notice("Select at least two non-central sibling nodes to group.");
      return;
    }
    const parent = refs[0].ref.parent;
    if (!refs.every((entry) => entry.ref.parent === parent)) {
      new import_obsidian2.Notice("Select sibling nodes under the same parent to group.");
      return;
    }
    const ordered = refs.sort((a, b) => a.ref.index - b.ref.index).map((entry) => parent.children[entry.ref.index]);
    const defaultName = ordered.map((node) => node.content).join(" + ");
    new TextInputModal(this.app, "Group node name", defaultName, (groupName) => {
      this.runCommand("Group nodes", () => {
        if (!this.data) return false;
        const groupNode = groupSiblingNodes(
          this.data.root,
          refs.map((entry) => entry.id),
          groupName.trim() || defaultName,
          getGroupPosition(ordered[0], ordered[ordered.length - 1])
        );
        if (!groupNode) return false;
        this.state.selectedNodeId = groupNode.id;
        this.selectedNodeIds = /* @__PURE__ */ new Set([groupNode.id]);
        this.connectSourceId = null;
        this.mergeSourceId = null;
      });
    }).open();
  }
  autoLayout() {
    if (!this.data) return;
    this.runCommand("Auto layout", () => {
      if (!this.data) return false;
      clearPositions(this.data.root);
      this.connectSourceId = null;
      this.mergeSourceId = null;
      this.editingNodeId = null;
    });
  }
  moveNode(nodeId, position) {
    if (!this.data) return;
    const node = findNode(this.data.root, nodeId);
    if (!node) return;
    this.runCommand("Move node", () => {
      if (!this.data) return false;
      if (!moveNode(this.data.root, nodeId, position)) return false;
      this.state.selectedNodeId = nodeId;
      this.selectedNodeIds = /* @__PURE__ */ new Set([nodeId]);
      this.editingNodeId = null;
    });
  }
  dropNode(nodeId, targetNodeId, position, merge) {
    if (!this.data || !targetNodeId) {
      this.moveNode(nodeId, position);
      return;
    }
    if (merge) {
      if (!this.mergeNodes(nodeId, targetNodeId)) {
        this.moveNode(nodeId, position);
      }
      return;
    }
    if (!this.runCommand("Reparent node", () => {
      if (!this.data) return false;
      if (!reparentNode(this.data.root, nodeId, targetNodeId, position)) return false;
      this.state.selectedNodeId = nodeId;
      this.selectedNodeIds = /* @__PURE__ */ new Set([nodeId]);
      this.connectSourceId = null;
      this.mergeSourceId = null;
      this.editingNodeId = null;
    })) {
      this.moveNode(nodeId, position);
    }
  }
  connectNodes(fromNodeId, toNodeId) {
    if (!this.data) return;
    if (fromNodeId === toNodeId) {
      this.connectSourceId = null;
      this.render();
      return;
    }
    const fromNode = findNode(this.data.root, fromNodeId);
    const toNode = findNode(this.data.root, toNodeId);
    if (!fromNode || !toNode) {
      new import_obsidian2.Notice("Could not connect these nodes.");
      return;
    }
    if (!this.runCommand("Connect nodes", () => {
      var _a;
      if (!this.data) return false;
      const connections = (_a = this.data.connections) != null ? _a : [];
      const exists = connections.some(
        (connection) => connection.fromNodeId === fromNodeId && connection.toNodeId === toNodeId
      );
      if (exists) {
        return false;
      }
      this.data.connections = [
        ...connections,
        {
          id: crypto.randomUUID(),
          fromNodeId,
          toNodeId
        }
      ];
      this.state.selectedNodeId = toNodeId;
      this.selectedNodeIds = /* @__PURE__ */ new Set([toNodeId]);
      this.connectSourceId = null;
      this.mergeSourceId = null;
      this.editingNodeId = null;
    })) {
      new import_obsidian2.Notice("These nodes are already connected.");
      this.connectSourceId = null;
      this.render();
    }
  }
  mergeNodes(sourceNodeId, targetNodeId) {
    if (!this.data || sourceNodeId === targetNodeId) return false;
    if (sourceNodeId === this.data.root.id) return false;
    if (targetNodeId === this.data.root.id) return false;
    const sourceRef = findChildRef(this.data.root, sourceNodeId);
    const targetRef = findChildRef(this.data.root, targetNodeId);
    if (!sourceRef || !targetRef || sourceRef.parent !== targetRef.parent) {
      new import_obsidian2.Notice("Merge only works for sibling nodes under the same parent.");
      return false;
    }
    const parent = sourceRef.parent;
    const firstIndex = Math.min(sourceRef.index, targetRef.index);
    const secondIndex = Math.max(sourceRef.index, targetRef.index);
    const firstNode = parent.children[firstIndex];
    const secondNode = parent.children[secondIndex];
    const position = getGroupPosition(firstNode, secondNode);
    const defaultGroupName = this.getDefaultGroupName(firstNode, secondNode);
    new TextInputModal(this.app, "Merged node name", defaultGroupName, (groupName) => {
      this.runCommand("Merge nodes", () => {
        if (!this.data) return false;
        const groupNode = groupSiblingNodes(
          this.data.root,
          [firstNode.id, secondNode.id],
          groupName.trim() || defaultGroupName,
          position
        );
        if (!groupNode) return false;
        this.state.selectedNodeId = groupNode.id;
        this.selectedNodeIds = /* @__PURE__ */ new Set([groupNode.id]);
        this.connectSourceId = null;
        this.mergeSourceId = null;
        this.editingNodeId = null;
      });
    }).open();
    return true;
  }
  deleteNode(nodeId = this.state.selectedNodeId) {
    if (!this.data || !nodeId) {
      new import_obsidian2.Notice("Select a node to delete.");
      return;
    }
    if (nodeId === this.data.root.id) {
      new import_obsidian2.Notice("The central node cannot be deleted.");
      return;
    }
    const node = findNode(this.data.root, nodeId);
    if (!node) {
      new import_obsidian2.Notice("Selected node was not found.");
      return;
    }
    if (node.children.length > 0) {
      new ConfirmModal(
        this.app,
        "Delete node",
        `Delete "${node.content}" and all child nodes?`,
        () => this.deleteNodeNow(nodeId)
      ).open();
      return;
    }
    this.deleteNodeNow(nodeId);
  }
  deleteNodeNow(nodeId) {
    if (!this.data || nodeId === this.data.root.id) return;
    const parent = findParent(this.data.root, nodeId);
    if (parent) {
      this.runCommand("Delete node", () => {
        if (!this.data) return false;
        if (!deleteNode(this.data.root, nodeId)) return false;
        this.removeConnectionsForNode(nodeId);
        this.state.selectedNodeId = parent.id;
        this.selectedNodeIds = /* @__PURE__ */ new Set([parent.id]);
        this.connectSourceId = null;
        this.mergeSourceId = null;
        this.editingNodeId = null;
      });
    }
  }
  removeConnectionsForNode(nodeId) {
    var _a;
    if (!((_a = this.data) == null ? void 0 : _a.connections)) return;
    this.data.connections = this.data.connections.filter(
      (connection) => connection.fromNodeId !== nodeId && connection.toNodeId !== nodeId
    );
  }
  toggleCollapse(nodeId = this.state.selectedNodeId) {
    if (!this.data || !nodeId) {
      new import_obsidian2.Notice("Select a node to collapse or expand.");
      return;
    }
    const node = findNode(this.data.root, nodeId);
    if (node && node.children.length > 0) {
      this.runCommand("Toggle collapse", () => {
        if (!this.data) return false;
        if (!toggleCollapse(this.data.root, nodeId)) return false;
        this.state.selectedNodeId = node.id;
        this.selectedNodeIds = /* @__PURE__ */ new Set([node.id]);
        this.connectSourceId = null;
        this.mergeSourceId = null;
        this.editingNodeId = null;
      });
    } else {
      new import_obsidian2.Notice("Only nodes with children can collapse or expand.");
    }
  }
  getChildPosition(parent) {
    var _a;
    const base = (_a = parent.position) != null ? _a : { x: 160, y: 72 };
    return {
      x: base.x + 240,
      y: base.y + Math.max(parent.children.length, 0) * 88
    };
  }
  getSiblingPosition(nodeId) {
    var _a;
    const node = this.data ? findNode(this.data.root, nodeId) : null;
    const base = (_a = node == null ? void 0 : node.position) != null ? _a : { x: 160, y: 72 };
    return {
      x: base.x,
      y: base.y + 88
    };
  }
  getDefaultGroupName(firstNode, secondNode) {
    return `${firstNode.content} + ${secondNode.content}`;
  }
  renderMinimap() {
    var _a;
    if (!this.data || !this.minimapEl) return;
    const root = this.data.root;
    const positions = layoutTree(root);
    const visibleNodes = this.getVisibleNodes(root);
    for (const node of visibleNodes) {
      if (node.position) positions.set(node.id, node.position);
    }
    let minX = Infinity;
    let minY = Infinity;
    let maxX = -Infinity;
    let maxY = -Infinity;
    for (const node of visibleNodes) {
      const pos = positions.get(node.id);
      if (!pos) continue;
      minX = Math.min(minX, pos.x - 80);
      minY = Math.min(minY, pos.y);
      maxX = Math.max(maxX, pos.x + 80);
      maxY = Math.max(maxY, pos.y + 48);
    }
    if (!Number.isFinite(minX) || !Number.isFinite(minY)) return;
    const width = 180;
    const height = 120;
    const mapWidth = Math.max(1, maxX - minX);
    const mapHeight = Math.max(1, maxY - minY);
    const scale = Math.min((width - 16) / mapWidth, (height - 16) / mapHeight);
    const tx = 8 - minX * scale;
    const ty = 8 - minY * scale;
    this.minimapEl.empty();
    const svg = activeDocument.createElementNS("http://www.w3.org/2000/svg", "svg");
    svg.setAttribute("viewBox", `0 0 ${width} ${height}`);
    svg.setAttribute("class", "mindmap-minimap-svg");
    const drawNode = (node) => {
      const from = positions.get(node.id);
      if (!from) return;
      if (!node.collapsed) {
        for (const child of node.children) {
          const to = positions.get(child.id);
          if (to) {
            const line = activeDocument.createElementNS("http://www.w3.org/2000/svg", "line");
            line.setAttribute("x1", String(from.x * scale + tx));
            line.setAttribute("y1", String((from.y + 24) * scale + ty));
            line.setAttribute("x2", String(to.x * scale + tx));
            line.setAttribute("y2", String((to.y + 24) * scale + ty));
            line.setAttribute("class", "mindmap-minimap-edge");
            svg.appendChild(line);
          }
          drawNode(child);
        }
      }
      const rect = activeDocument.createElementNS("http://www.w3.org/2000/svg", "rect");
      rect.setAttribute("x", String((from.x - 80) * scale + tx));
      rect.setAttribute("y", String(from.y * scale + ty));
      rect.setAttribute("width", String(160 * scale));
      rect.setAttribute("height", String(48 * scale));
      rect.setAttribute("rx", "2");
      rect.setAttribute("class", this.selectedNodeIds.has(node.id) ? "mindmap-minimap-node is-selected" : "mindmap-minimap-node");
      svg.appendChild(rect);
    };
    drawNode(root);
    const viewport = (_a = this.canvas) == null ? void 0 : _a.getViewportSize();
    if (viewport) {
      const rect = activeDocument.createElementNS("http://www.w3.org/2000/svg", "rect");
      rect.setAttribute("x", String(-this.state.pan.x * scale + tx));
      rect.setAttribute("y", String(-this.state.pan.y * scale + ty));
      rect.setAttribute("width", String(viewport.width / this.state.zoom * scale));
      rect.setAttribute("height", String(viewport.height / this.state.zoom * scale));
      rect.setAttribute("class", "mindmap-minimap-viewport");
      svg.appendChild(rect);
    }
    this.minimapEl.appendChild(svg);
  }
  getVisibleNodes(root) {
    const nodes = [];
    const visit = (node) => {
      nodes.push(node);
      if (!node.collapsed) node.children.forEach(visit);
    };
    visit(root);
    return nodes;
  }
  setupSpacePanHandlers() {
    this.registerDomEvent(window, "keydown", (event) => {
      if (event.code === "Space" && !this.isTextInputTarget(event.target)) {
        this.isSpacePanPressed = true;
      }
    });
    this.registerDomEvent(window, "keyup", (event) => {
      var _a;
      if (event.code === "Space") {
        this.isSpacePanPressed = false;
        (_a = this.containerEl.querySelector(".mindmap-canvas")) == null ? void 0 : _a.removeClass("is-space-pan");
      }
    });
  }
};
var TextInputModal = class extends import_obsidian2.Modal {
  constructor(app, title, initialValue, onSubmit) {
    super(app);
    this.title = title;
    this.initialValue = initialValue;
    this.onSubmit = onSubmit;
  }
  onOpen() {
    this.setTitle(this.title);
    this.contentEl.empty();
    this.contentEl.addClass("mindmap-text-modal");
    const input = this.contentEl.createEl("input", {
      type: "text",
      value: this.initialValue
    });
    input.addClass("mindmap-text-modal-input");
    const buttons = this.contentEl.createDiv("mindmap-text-modal-buttons");
    const cancelButton = buttons.createEl("button", { text: "Cancel" });
    const saveButton = buttons.createEl("button", { text: "Save" });
    saveButton.addClass("mod-cta");
    const submit = () => {
      this.onSubmit(input.value);
      this.close();
    };
    input.addEventListener("keydown", (event) => {
      if (event.key === "Enter") {
        event.preventDefault();
        submit();
      }
      if (event.key === "Escape") {
        event.preventDefault();
        this.close();
      }
    });
    cancelButton.addEventListener("click", () => this.close());
    saveButton.addEventListener("click", submit);
    window.setTimeout(() => {
      input.focus();
      input.select();
    }, 0);
  }
  onClose() {
    this.contentEl.empty();
  }
};
var NodeNoteModal = class extends import_obsidian2.Modal {
  constructor(app, nodeTitle, initialValue, onSubmit) {
    super(app);
    this.nodeTitle = nodeTitle;
    this.initialValue = initialValue;
    this.onSubmit = onSubmit;
  }
  onOpen() {
    this.setTitle(`Node note: ${this.nodeTitle}`);
    this.modalEl.addClass("mindmap-node-note-modal-shell");
    this.contentEl.empty();
    this.contentEl.addClass("mindmap-node-note-modal");
    const textarea = this.contentEl.createEl("textarea");
    textarea.addClass("mindmap-node-note-textarea");
    textarea.value = this.initialValue;
    const buttons = this.contentEl.createDiv("mindmap-text-modal-buttons");
    const clearButton = buttons.createEl("button", { text: "Clear" });
    const cancelButton = buttons.createEl("button", { text: "Cancel" });
    const saveButton = buttons.createEl("button", { text: "Save" });
    saveButton.addClass("mod-cta");
    clearButton.addEventListener("click", () => {
      textarea.value = "";
      textarea.focus();
    });
    cancelButton.addEventListener("click", () => this.close());
    saveButton.addEventListener("click", () => {
      this.onSubmit(textarea.value);
      this.close();
    });
    textarea.addEventListener("keydown", (event) => {
      if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "s") {
        event.preventDefault();
        this.onSubmit(textarea.value);
        this.close();
      }
      if (event.key === "Escape") {
        event.preventDefault();
        this.close();
      }
    });
    window.setTimeout(() => {
      textarea.focus();
      textarea.setSelectionRange(textarea.value.length, textarea.value.length);
    }, 0);
  }
  onClose() {
    this.modalEl.removeClass("mindmap-node-note-modal-shell");
    this.contentEl.empty();
  }
};
var GuideModal = class extends import_obsidian2.Modal {
  constructor(app) {
    super(app);
  }
  onOpen() {
    this.setTitle("Mind Map Guide");
    this.contentEl.empty();
    this.contentEl.addClass("mindmap-guide-modal");
    this.addSection("Toolbar buttons", [
      ["Zoom - / Zoom +", "Change map zoom."],
      ["100%", "Reset zoom to default."],
      ["Fit", "Fit the full map into the current view."],
      ["Undo / Redo", "Step backward or forward through map edits."],
      ["Add child", "Create a child under the selected node."],
      ["Add sibling", "Create a sibling next to the selected node."],
      ["Rename", "Start inline rename for the selected node."],
      ["Connect", "Select a source node, click Connect, then click a target node to add a dashed cross-link without changing the tree."],
      ["Merge", "Select one sibling, click Merge, then click another sibling to create one grouped node."],
      ["Group", "Group two or more selected sibling nodes into one parent node."],
      ["Auto layout", "Clear manual node positions and rebuild the tree layout."],
      ["Delete", "Delete the selected node. The central node is protected."],
      ["Save", "Write the current mind map to the Obsidian note."],
      ["Download", "Export the full mind map as PNG, JPEG, or PDF."]
    ]);
    this.addSection("Open a saved mind map", [
      ["1", "Open the saved mind map Markdown note in Obsidian."],
      ["2", "Open the Command palette with Cmd/Ctrl + P."],
      ["3", "Run \u201CMind map: Open current file as mind map\u201D."]
    ]);
    this.addSection("Node gestures", [
      ["Click", "Select a node."],
      ["Shift + click", "Add or remove a node from the current selection."],
      ["Double-click", "Rename a node inline."],
      ["Drag node", "Move a node."],
      ["Drag node onto another node", "Move it under the target node."],
      ["Shift + drag node onto sibling", "Merge with the drop target when possible."],
      ["Right-click node", "Open node actions: edit label, edit long note, create/open linked note, delete."],
      ["+ handle", "Add a child node."],
      ["- / + left handle", "Collapse or expand child nodes."],
      ["x handle", "Delete a node."]
    ]);
    this.addSection("Canvas gestures", [
      ["Mouse wheel", "Zoom in or out."],
      ["Drag empty canvas", "Pan the map."],
      ["Middle mouse drag", "Pan the map."],
      ["Hold Space + drag", "Pan the map from anywhere."],
      ["Shift + drag empty canvas", "Draw a box to multi-select nodes."]
    ]);
    this.addSection("Hotkeys", [
      ["Tab", "Add child."],
      ["Enter", "Add sibling."],
      ["F2", "Rename selected node."],
      ["Delete / Backspace", "Delete selected node."],
      ["Cmd/Ctrl + Z", "Undo."],
      ["Cmd/Ctrl + Shift + Z", "Redo."],
      ["Cmd/Ctrl + S", "Save."],
      ["Cmd/Ctrl + +", "Zoom in and center the selected node."],
      ["Cmd/Ctrl + -", "Zoom out and center the selected node."],
      ["Cmd/Ctrl + 0", "Reset zoom to 100%."],
      ["Cmd/Ctrl + /", "Open this guide."]
    ]);
  }
  addSection(title, rows) {
    this.contentEl.createEl("h3", { text: title });
    const table = this.contentEl.createEl("table");
    table.addClass("mindmap-guide-table");
    const tbody = table.createEl("tbody");
    for (const [name, description] of rows) {
      const row = tbody.createEl("tr");
      row.createEl("th", { text: name });
      row.createEl("td", { text: description });
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};
var ConfirmModal = class extends import_obsidian2.Modal {
  constructor(app, title, message, onConfirm) {
    super(app);
    this.title = title;
    this.message = message;
    this.onConfirm = onConfirm;
  }
  onOpen() {
    this.setTitle(this.title);
    this.contentEl.empty();
    this.contentEl.addClass("mindmap-confirm-modal");
    this.contentEl.createEl("p", { text: this.message });
    const buttons = this.contentEl.createDiv("mindmap-text-modal-buttons");
    const cancelButton = buttons.createEl("button", { text: "Cancel" });
    const confirmButton = buttons.createEl("button", { text: "Delete" });
    confirmButton.addClass("mod-warning");
    cancelButton.addEventListener("click", () => this.close());
    confirmButton.addEventListener("click", () => {
      this.onConfirm();
      this.close();
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/commands/index.ts
function registerCommands(app, plugin) {
  plugin.addCommand({
    id: "obsidian-mindmap-create",
    name: "Mind map: Create new mind map",
    callback: async () => {
      const leaf = app.workspace.getLeaf("tab");
      await leaf.setViewState({ type: VIEW_TYPE, active: true });
      const view = leaf.view;
      if (view instanceof MindMapView) {
        view.createNew();
      }
    }
  });
  plugin.addCommand({
    id: "obsidian-mindmap-open",
    name: "Mind map: Open current file as mind map",
    checkCallback: (checking) => {
      const activeFile = app.workspace.getActiveFile();
      if (!activeFile) return false;
      if (!checking) {
        void (async () => {
          const leaf = app.workspace.getLeaf("tab");
          await leaf.setViewState({ type: VIEW_TYPE, active: true });
          const view = leaf.view;
          if (view instanceof MindMapView) {
            await view.loadFile(activeFile.path);
          }
        })();
      }
      return true;
    }
  });
  plugin.addCommand({
    id: "obsidian-mindmap-save",
    name: "Mind map: Save current mind map",
    checkCallback: (checking) => {
      const view = app.workspace.getActiveViewOfType(MindMapView);
      if (!view) {
        return false;
      }
      if (!checking) {
        void view.save();
      }
      return true;
    }
  });
}

// src/settings.ts
var import_obsidian3 = require("obsidian");
var MindMapSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian3.Setting(containerEl).setName("Mind Map").setHeading();
    containerEl.createEl("p", {
      text: "Additional settings will be added in future versions."
    });
  }
};

// src/main.ts
var MindMapPlugin = class extends import_obsidian4.Plugin {
  async onload() {
    console.log("Loading Mind Map plugin");
    this.registerView(
      VIEW_TYPE,
      (leaf) => new MindMapView(leaf)
    );
    registerCommands(this.app, this);
    const ribbonIcon = this.addRibbonIcon("map", "Mind Map", async () => {
      const leaf = this.app.workspace.getLeaf("tab");
      await leaf.setViewState({ type: VIEW_TYPE, active: true });
      const view = leaf.view;
      if (view instanceof MindMapView) {
        view.createNew();
      }
    });
    ribbonIcon.addClass("mindmap-ribbon-icon");
    this.addSettingTab(new MindMapSettingTab(this.app, this));
  }
  onunload() {
    console.log("Unloading Mind Map plugin");
  }
};

/* nosourcemap */